'use server';

import { z } from 'zod';
import { getServerSupabase, requireServerUser } from '@/lib/supabase/server';

export const propertySchema = z.object({ category: z.enum(['rumah_sewa','kos_kosan','rumah_takeover','lelang','rumah_subsidi']), title: z.string().trim().min(5).max(140), description: z.string().trim().max(4000).optional(), price: z.coerce.number().min(0), priceType: z.enum(['per_bulan','per_tahun','total','mulai_dari']), landAreaSqm: z.coerce.number().int().nonnegative().optional(), buildingAreaSqm: z.coerce.number().int().nonnegative().optional(), bedrooms: z.coerce.number().int().nonnegative().default(0), bathrooms: z.coerce.number().int().nonnegative().default(0), furnished: z.boolean().default(false), district: z.string().trim().min(2).max(80), city: z.string().trim().default('Kendari'), addressDetail: z.string().trim().max(400).optional(), mapsLink: z.string().url().optional().or(z.literal('')), shmStatus: z.string().trim().max(40).optional(), images: z.array(z.string().url()).max(12).default([]), videoUrl: z.string().url().optional().or(z.literal('')) });
export type PropertyInput = z.infer<typeof propertySchema>;
const errorMessage = (error: unknown) => error instanceof Error ? error.message : 'Properti belum dapat diproses.';

export async function getProperties(filters: { category?: PropertyInput['category']; district?: string; minPrice?: number; maxPrice?: number } = {}) { try { const supabase = getServerSupabase(); let query = supabase.from('properties').select('id,seller_id,category,title,description,price,price_type,land_area_sqm,building_area_sqm,bedrooms,bathrooms,furnished,district,city,address_detail,maps_link,shm_status,is_bank_verified,images,video_url,status,is_featured,created_at').eq('status', 'available').order('is_featured', { ascending: false }).order('created_at', { ascending: false }).limit(40); if (filters.category) query = query.eq('category', filters.category); if (filters.district) query = query.eq('district', filters.district); if (filters.minPrice !== undefined) query = query.gte('price', filters.minPrice); if (filters.maxPrice !== undefined) query = query.lte('price', filters.maxPrice); const { data, error } = await query; if (error) throw error; return { ok: true as const, data: data || [] }; } catch (error) { return { ok: false as const, error: errorMessage(error), data: [] }; } }

export async function createProperty(input: PropertyInput) { try { const parsed = propertySchema.parse(input); const { supabase, user } = await requireServerUser(); const { data, error } = await supabase.from('properties').insert({ seller_id: user.id, category: parsed.category, title: parsed.title, description: parsed.description || null, price: parsed.price, price_type: parsed.priceType, land_area_sqm: parsed.landAreaSqm ?? null, building_area_sqm: parsed.buildingAreaSqm ?? null, bedrooms: parsed.bedrooms, bathrooms: parsed.bathrooms, furnished: parsed.furnished, district: parsed.district, city: parsed.city, address_detail: parsed.addressDetail || null, maps_link: parsed.mapsLink || null, shm_status: parsed.shmStatus || null, images: parsed.images, video_url: parsed.videoUrl || null, status: 'available' }).select('id,title,category,status').single(); if (error) throw error; return { ok: true as const, data }; } catch (error) { return { ok: false as const, error: errorMessage(error) }; } }

export async function updatePropertyStatus(id: string, status: 'available' | 'rented' | 'sold' | 'archived') { try { const { supabase, user } = await requireServerUser(); const { data, error } = await supabase.from('properties').update({ status }).eq('id', id).eq('seller_id', user.id).select('id,status').single(); if (error) throw error; return { ok: true as const, data }; } catch (error) { return { ok: false as const, error: errorMessage(error) }; } }
