'use server';

import { z } from 'zod';
import { getServerSupabase, requireServerUser } from '@/lib/supabase/server';
const ticketSchema = z.object({ category: z.enum(['technical','fraud','payment','listing','account','other']), subject: z.string().trim().min(5).max(160), description: z.string().trim().min(15).max(5000), priority: z.enum(['low','medium','high','critical']).default('medium'), relatedListingId: z.string().uuid().optional(), reportedUserId: z.string().uuid().optional(), screenshots: z.array(z.string().url()).max(5).default([]) });
export type TicketInput = z.infer<typeof ticketSchema>;
const message = (error: unknown) => error instanceof Error ? error.message : 'Permintaan support belum dapat diproses.';
export async function createSupportTicket(input: unknown) { try { const parsed = ticketSchema.parse(input); const { supabase, user } = await requireServerUser(); const { data, error } = await supabase.from('support_tickets').insert({ user_id: user.id, ticket_number: '', subject: parsed.subject, description: parsed.description, category: parsed.category, priority: parsed.priority, related_listing_id: parsed.relatedListingId || null, reported_user_id: parsed.reportedUserId || null, screenshots: parsed.screenshots }).select('id,ticket_number,status,created_at').single(); if (error) throw error; return { ok: true as const, data }; } catch (error) { return { ok: false as const, error: message(error) }; } }
export async function getSupportTicket(id: string) { try { const { supabase, user } = await requireServerUser(); const { data, error } = await supabase.from('support_tickets').select('id,ticket_number,subject,description,category,priority,status,screenshots,admin_response,resolved_at,created_at,updated_at').eq('id', id).eq('user_id', user.id).maybeSingle(); if (error) throw error; return { ok: true as const, data }; } catch (error) { return { ok: false as const, error: message(error) }; } }
export async function getMySupportTickets() { try { const { supabase, user } = await requireServerUser(); const { data, error } = await supabase.from('support_tickets').select('id,ticket_number,subject,category,priority,status,created_at,updated_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(50); if (error) throw error; return { ok: true as const, data: data || [] }; } catch (error) { return { ok: false as const, error: message(error), data: [] }; } }
export async function getHelpArticles(query?: string, category?: string) { try { const supabase = getServerSupabase(); let request = supabase.from('help_articles').select('id,title,slug,content,category,tags,views_count,published_at,updated_at').eq('is_published', true).order('views_count', { ascending: false }).limit(20); if (query) request = request.or(`title.ilike.%${query}%,content.ilike.%${query}%`); if (category) request = request.eq('category', category); const { data, error } = await request; if (error) throw error; return { ok: true as const, data: data || [] }; } catch (error) { return { ok: false as const, error: message(error), data: [] }; } }
export async function getHelpArticle(slug: string) { try { const supabase = getServerSupabase(); const { data, error } = await supabase.from('help_articles').select('id,title,slug,content,category,tags,views_count,published_at,updated_at').eq('slug', slug).eq('is_published', true).maybeSingle(); if (error) throw error; return { ok: true as const, data }; } catch (error) { return { ok: false as const, error: message(error) }; } }
export async function listAdminSupportTickets(filters: { status?: string; priority?: string } = {}) { try { const { supabase, user } = await requireServerUser(); const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).maybeSingle(); if (profile?.role !== 'admin') throw new Error('Akses admin diperlukan.'); let request = supabase.from('support_tickets').select('id,ticket_number,user_id,subject,description,category,priority,status,admin_response,created_at,updated_at').order('created_at', { ascending: false }).limit(100); if (filters.status) request = request.eq('status', filters.status); if (filters.priority) request = request.eq('priority', filters.priority); const { data, error } = await request; if (error) throw error; return { ok: true as const, data: data || [] }; } catch (error) { return { ok: false as const, error: message(error), data: [] }; } }
export async function updateSupportTicket(id: string, status: 'open'|'in_progress'|'waiting_user'|'resolved'|'closed', adminResponse?: string) { try { const { supabase, user } = await requireServerUser(); const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).maybeSingle(); if (profile?.role !== 'admin') throw new Error('Akses admin diperlukan.'); const { data, error } = await supabase.from('support_tickets').update({ status, admin_response: adminResponse || null, resolved_at: status === 'resolved' ? new Date().toISOString() : null, resolved_by: status === 'resolved' ? user.id : null }).eq('id', id).select('id,status,updated_at').single(); if (error) throw error; return { ok: true as const, data }; } catch (error) { return { ok: false as const, error: message(error) }; } }
