-- SultraKita Supabase blueprint
-- Jalankan hanya pada proyek Supabase yang memang disiapkan untuk UUID/auth.users.
create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'Pengguna Sultra',
  phone text unique,
  avatar_url text,
  bio text,
  role text not null default 'buyer' check (role in ('buyer','seller','admin')),
  is_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  icon text,
  created_at timestamptz not null default now()
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  level text not null check (level in ('province','regency','district','village')),
  parent_id bigint references public.locations(id) on delete cascade,
  latitude numeric(9,6),
  longitude numeric(9,6),
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.users(id) on delete cascade,
  category_id bigint not null references public.categories(id),
  location_id bigint not null references public.locations(id),
  title text not null check (char_length(title) between 5 and 120),
  slug text not null,
  description text not null check (char_length(description) between 10 and 5000),
  price bigint not null check (price >= 0),
  condition text not null default 'second' check (condition in ('new','second')),
  status text not null default 'pending' check (status in ('pending','active','sold','rejected','archived')),
  image_urls text[] not null default '{}',
  specs jsonb not null default '{}'::jsonb,
  search_vector tsvector generated always as (to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(description,''))) stored,
  views integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (seller_id, slug)
);

create table if not exists public.whatsapp_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  purpose text not null default 'magic_link' check (purpose in ('magic_link','phone_verification')),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references public.users(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, listing_id)
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.users(id) on delete cascade,
  listing_id bigint references public.listings(id) on delete cascade,
  reported_user_id uuid references public.users(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 500),
  status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')),
  created_at timestamptz not null default now(),
  check (listing_id is not null or reported_user_id is not null)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  link text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  listing_id bigint references public.listings(id) on delete set null,
  reviewer_id uuid not null references public.users(id) on delete cascade,
  reviewee_id uuid not null references public.users(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  body text check (char_length(body) <= 1000),
  created_at timestamptz not null default now(),
  unique (listing_id, reviewer_id, reviewee_id)
);

create index if not exists listings_search_idx on public.listings using gin(search_vector);
create index if not exists listings_title_trgm_idx on public.listings using gin(title gin_trgm_ops);
create index if not exists listings_category_idx on public.listings(category_id, status, created_at desc);
create index if not exists listings_location_idx on public.listings(location_id, status, created_at desc);
create index if not exists locations_parent_idx on public.locations(parent_id, level);
create index if not exists locations_slug_idx on public.locations(slug);
create index if not exists favorites_user_idx on public.favorites(user_id, created_at desc);
create index if not exists reports_status_idx on public.reports(status, created_at desc);
create index if not exists notifications_user_idx on public.notifications(user_id, read_at, created_at desc);
create index if not exists reviews_reviewee_idx on public.reviews(reviewee_id, created_at desc);
create index if not exists whatsapp_tokens_expiry_idx on public.whatsapp_tokens(expires_at) where consumed_at is null;

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.locations enable row level security;
alter table public.listings enable row level security;
alter table public.whatsapp_tokens enable row level security;
alter table public.reviews enable row level security;
alter table public.favorites enable row level security;
alter table public.reports enable row level security;
alter table public.notifications enable row level security;

create policy "public can read categories" on public.categories for select using (true);
create policy "public can read locations" on public.locations for select using (true);
create policy "public can read active listings" on public.listings for select using (status = 'active' or seller_id = auth.uid());
create policy "sellers create own listings" on public.listings for insert with check (seller_id = auth.uid());
create policy "sellers update own listings" on public.listings for update using (seller_id = auth.uid()) with check (seller_id = auth.uid());
create policy "sellers delete own listings" on public.listings for delete using (seller_id = auth.uid());
create policy "users read own profile" on public.users for select using (id = auth.uid());
create policy "users update own profile" on public.users for update using (id = auth.uid()) with check (id = auth.uid());
create policy "public read reviews" on public.reviews for select using (true);
create policy "users manage own favorites" on public.favorites for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users create reports" on public.reports for insert with check (reporter_id = auth.uid());
create policy "users read own reports" on public.reports for select using (reporter_id = auth.uid());
create policy "users read own notifications" on public.notifications for select using (user_id = auth.uid());
create policy "users update own notifications" on public.notifications for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users create reviews" on public.reviews for insert with check (reviewer_id = auth.uid());
create policy "users manage own whatsapp tokens" on public.whatsapp_tokens for all using (user_id = auth.uid()) with check (user_id = auth.uid());

insert into public.categories(name, slug, icon) values
  ('Elektronik', 'elektronik', '▣'), ('Kendaraan', 'kendaraan', '◉'), ('Properti', 'properti', '⌂'),
  ('Fashion', 'fashion', '✦'), ('Jasa', 'jasa', '◌'), ('Rumah Tangga', 'rumah-tangga', '▦'),
  ('Hobi & Koleksi', 'hobi-koleksi', '♢'), ('Lowongan Kerja', 'lowongan-kerja', '↗')
on conflict (slug) do nothing;

insert into public.locations(name, slug, level) values
  ('Sulawesi Tenggara', 'sulawesi-tenggara', 'province'),
  ('Kota Kendari', 'kota-kendari', 'regency'),
  ('Kabupaten Konawe', 'kabupaten-konawe', 'regency'),
  ('Kabupaten Konawe Selatan', 'kabupaten-konawe-selatan', 'regency'),
  ('Kabupaten Kolaka', 'kabupaten-kolaka', 'regency'),
  ('Kabupaten Muna', 'kabupaten-muna', 'regency'),
  ('Kabupaten Buton', 'kabupaten-buton', 'regency')
on conflict (slug) do nothing;

comment on table public.whatsapp_tokens is 'Store only hashes; use short-lived tokens for magic-link verification and never expose raw tokens in logs.';
