'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
test('launch referral campaign contract is present', () => {
  const migration = fs.readFileSync(path.join(root, 'database/migrations/026_referral_launch_campaign.sql'), 'utf8');
  const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
  const page = fs.readFileSync(path.join(root, 'public/referral/index.html'), 'utf8');
  const nextApi = fs.readFileSync(path.join(root, 'next-app/app/api/referral/route.ts'), 'utf8');
  const authMigration = fs.readFileSync(path.join(root, 'database/migrations/027_referral_auth_accounts.sql'), 'utf8');
  const atomicMigration = fs.readFileSync(path.join(root, 'database/migrations/028_referral_atomic_operations.sql'), 'utf8');
  const ledgerMigration = fs.readFileSync(path.join(root, 'database/migrations/031_referral_reward_ledger.sql'), 'utf8');
  const payoutMigration = fs.readFileSync(path.join(root, 'database/migrations/029_referral_payout_workflow.sql'), 'utf8');
  const notificationMigration = fs.readFileSync(path.join(root, 'database/migrations/030_referral_payout_notifications.sql'), 'utf8');
  const payoutPage = fs.readFileSync(path.join(root, 'next-app/app/admin/affiliate-rewards/page.tsx'), 'utf8');
  const notificationCenter = fs.readFileSync(path.join(root, 'next-app/components/layout/NotificationCenter.tsx'), 'utf8');
  assert.match(migration, /CREATE TABLE IF NOT EXISTS referral_profiles/);
  assert.match(migration, /CREATE TABLE IF NOT EXISTS point_redemptions/);
  assert.match(server, /app\.use\('\/api\/referral', referralApi\)/);
  assert.match(server, /ajak-teman/);
  assert.match(page, /Ajak Teman, Tumbuh Bersama/);
  assert.match(page, /navigator\.share/);
  assert.match(nextApi, /action === 'qualified'/);
  assert.match(nextApi, /rpc\('qualify_referral'/);
  assert.match(nextApi, /create_referral_redemption/);
  assert.match(nextApi, /campaignClosed/);
  assert.match(authMigration, /REFERENCES auth\.users\(id\)/);
  assert.match(authMigration, /to_regclass\('auth\.users'\)/);
  assert.match(atomicMigration, /CREATE UNIQUE INDEX IF NOT EXISTS referral_account_one_pending_redemption_idx/);
  assert.match(atomicMigration, /REVOKE ALL ON FUNCTION/);
  assert.match(ledgerMigration, /CREATE TABLE IF NOT EXISTS public\.referral_reward_ledger/);
  assert.match(ledgerMigration, /idempotency_key TEXT NOT NULL UNIQUE/);
  assert.match(ledgerMigration, /CREATE OR REPLACE FUNCTION public\.qualify_referral/);
  assert.match(ledgerMigration, /ON CONFLICT \(event_key\) DO NOTHING/);
  assert.match(ledgerMigration, /qualified-award:/);
  assert.doesNotMatch(nextApi, /increment_referral_account_points/);
  assert.match(payoutMigration, /referral_redemption_audit_logs/);
  assert.match(payoutMigration, /transition_referral_payout/);
  assert.match(payoutMigration, /second operator required/);
  assert.match(payoutMigration, /p_to_status NOT IN \('approved','paid','rejected'\)/);
  assert.match(payoutMigration, /p_to_status = 'rejected' AND v_note IS NULL/);
  assert.match(payoutMigration, /p_to_status = 'paid' AND v_reference IS NULL/);
  assert.match(nextApi, /action === 'payout_queue'/);
  assert.match(nextApi, /action === 'payout_transition'/);
  assert.match(payoutPage, /pending/);
  assert.match(payoutPage, /approved/);
  assert.match(payoutPage, /paid/);
  assert.match(payoutPage, /rejected/);
  assert.match(payoutPage, /TWO-PERSON PAY/);
  assert.match(notificationMigration, /ALTER COLUMN user_id DROP NOT NULL/);
  assert.match(notificationMigration, /payout_status/);
  assert.match(notificationMigration, /jsonb_build_object\('status', p_to_status\)/);
  assert.match(notificationMigration, /profile_id, type, title, body, link, data, is_read/);
  assert.match(notificationMigration, /transition_referral_payout/);
  assert.match(notificationCenter, /from\('notifications'\)/);
  assert.match(notificationCenter, /postgres_changes/);
});
