import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput } from "react-native";
import { Stack, router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { createListing } from "@/lib/sultra-api";

export default function CreateListingScreen() {
  const colors = useColors();
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [price, setPrice] = useState(""); const [district, setDistrict] = useState("Kendari"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit() { if (title.trim().length < 5 || description.trim().length < 10 || !Number(price)) return setMessage("Lengkapi judul, deskripsi, dan harga terlebih dahulu."); setBusy(true); setMessage(""); const result = await createListing({ title: title.trim(), description: description.trim(), price: Number(price), category_id: 1, condition: "new", district: district.trim() || "Kendari" }); setBusy(false); if (result.error) return setMessage(result.error); setMessage("Listing berhasil dikirim untuk ditinjau."); setTimeout(() => router.back(), 700); }
  const inputStyle = [styles.input, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }];
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5" containerClassName="bg-background"><Stack.Screen options={{ headerShown: false }} /><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={[styles.back, { color: colors.primary }]}>‹  Kembali</Text></Pressable><Text style={[styles.kicker, { color: "#E87561" }]}>JUAL DI SULTRAKITA</Text><Text style={[styles.title, { color: colors.foreground }]}>Ceritakan apa yang kamu tawarkan.</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Listing akan melewati peninjauan agar ruang jual-beli tetap tepercaya.</Text><Text style={[styles.label, { color: colors.foreground }]}>Judul listing</Text><TextInput value={title} onChangeText={setTitle} placeholder="Contoh: Kamera mirrorless bekas" placeholderTextColor={colors.muted} style={inputStyle} /><Text style={[styles.label, { color: colors.foreground }]}>Harga</Text><TextInput value={price} onChangeText={setPrice} keyboardType="number-pad" placeholder="0" placeholderTextColor={colors.muted} style={inputStyle} /><Text style={[styles.label, { color: colors.foreground }]}>Distrik</Text><TextInput value={district} onChangeText={setDistrict} placeholder="Kendari" placeholderTextColor={colors.muted} style={inputStyle} /><Text style={[styles.label, { color: colors.foreground }]}>Deskripsi</Text><TextInput value={description} onChangeText={setDescription} multiline numberOfLines={5} textAlignVertical="top" placeholder="Tulis detail yang perlu diketahui pembeli..." placeholderTextColor={colors.muted} style={[...inputStyle, styles.textarea]} /><Pressable disabled={busy} onPress={submit} style={({ pressed }) => [styles.button, { backgroundColor: colors.primary, opacity: busy ? 0.55 : pressed ? 0.82 : 1 }]}><Text style={styles.buttonText}>{busy ? "Mengirim..." : "Kirim listing"}</Text></Pressable>{message ? <Text style={[styles.message, { color: colors.muted }]}>{message}</Text> : null}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 40 }, back: { fontSize: 16, fontWeight: "800", marginBottom: 24 }, kicker: { fontSize: 12, letterSpacing: 1.8, fontWeight: "800" }, title: { fontSize: 30, lineHeight: 36, fontWeight: "800", marginTop: 8 }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 10 }, label: { fontSize: 14, fontWeight: "800", marginTop: 22, marginBottom: 8 }, input: { minHeight: 54, borderRadius: 15, borderWidth: 1, paddingHorizontal: 15, fontSize: 15 }, textarea: { minHeight: 130, paddingTop: 14 }, button: { borderRadius: 15, alignItems: "center", paddingVertical: 16, marginTop: 28 }, buttonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, message: { textAlign: "center", marginTop: 14, lineHeight: 20 } });
