name = "sultrakita-demo"
main = "worker.js"
compatibility_date = "2026-08-22"
account_id = "1c6fef13342a46180a2f3826f88e8000"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "sultrakita-demo"
database_id = "f70de226-cfb5-4ec5-ad0f-73da5192163d"
