import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { searchListings, type Listing } from "@/lib/sultra-api";

export default function SearchScreen() {
  const colors = useColors();
  const [query, setQuery] = useState("");
  const [rows, setRows] = useState<Listing[]>([]);
  const [status, setStatus] = useState("Cari produk dan jasa dari warga sekitar.");
  async function search() { setStatus("Mencari di SultraKita..."); const result = await searchListings({ q: query }); setRows(result.data || []); setStatus(result.error || (result.data?.length ? `${result.data.length} hasil ditemukan` : "Belum ada hasil untuk pencarian ini.")); }
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.content}><Text style={[styles.kicker, { color: "#E87561" }]}>JELAJAHI LOKAL</Text><Text style={[styles.title, { color: colors.foreground }]}>Cari apa yang kamu butuhkan.</Text><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Contoh: motor, kos, desain logo" placeholderTextColor={colors.muted} returnKeyType="search" style={[styles.input, { color: colors.foreground }]} /><Pressable accessibilityRole="button" onPress={search} style={[styles.searchButton, { backgroundColor: colors.primary }]}><Text style={styles.searchButtonText}>Cari</Text></Pressable></View><Text style={[styles.status, { color: colors.muted }]}>{status}</Text><FlatList data={rows} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} renderItem={({ item }) => <Pressable onPress={() => router.push(`/listing/${item.id}`)} style={[styles.row, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.rowIcon, { backgroundColor: "#F5EBDD" }]}><Text style={{ color: colors.primary, fontWeight: "900" }}>SK</Text></View><View style={styles.rowCopy}><Text numberOfLines={1} style={[styles.rowTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.rowMeta, { color: colors.muted }]}>{item.district || item.city || "Sulawesi Tenggara"}</Text></View><Text style={[styles.chevron, { color: colors.primary }]}>›</Text></Pressable>} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Pencarian yang terasa dekat</Text><Text style={[styles.rowMeta, { color: colors.muted }]}>Listing dari warga sekitar akan muncul di sini.</Text></View>} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 18, flex: 1 }, kicker: { fontSize: 12, letterSpacing: 1.8, fontWeight: "800" }, title: { fontSize: 30, lineHeight: 36, fontWeight: "800", marginTop: 8 }, search: { height: 56, borderRadius: 16, borderWidth: 1, flexDirection: "row", alignItems: "center", paddingLeft: 15, marginTop: 22, overflow: "hidden" }, input: { flex: 1, fontSize: 15 }, searchButton: { height: "100%", paddingHorizontal: 18, alignItems: "center", justifyContent: "center" }, searchButtonText: { color: "#FFFFFF", fontWeight: "800" }, status: { fontSize: 13, marginTop: 14 }, list: { paddingVertical: 16, gap: 10 }, row: { borderWidth: 1, borderRadius: 16, padding: 13, flexDirection: "row", alignItems: "center" }, rowIcon: { width: 42, height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center" }, rowCopy: { flex: 1, marginLeft: 12 }, rowTitle: { fontSize: 15, fontWeight: "800" }, rowMeta: { fontSize: 13, lineHeight: 19, marginTop: 4 }, chevron: { fontSize: 28, marginLeft: 8 }, empty: { borderWidth: 1, borderRadius: 18, padding: 22, marginTop: 10 }, emptyTitle: { fontSize: 16, fontWeight: "800" } });
