import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { Image } from "expo-image";
import { Stack, useLocalSearchParams, router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { getListing, type Listing } from "@/lib/sultra-api";

export default function ListingDetailScreen() {
  const colors = useColors();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [listing, setListing] = useState<Listing>();
  const [error, setError] = useState("Memuat detail listing...");
  useEffect(() => { getListing(Number(id)).then((result) => { if (result.data) setListing(result.data); else setError(result.error || "Listing tidak ditemukan."); }); }, [id]);
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5" containerClassName="bg-background"><Stack.Screen options={{ title: "Detail listing", headerShown: false }} /><ScrollView contentContainerStyle={styles.content}>
    <Pressable accessibilityRole="button" accessibilityLabel="Kembali" onPress={() => router.back()}><Text style={[styles.back, { color: colors.primary }]}>‹  Kembali</Text></Pressable>
    {listing ? <><View style={styles.imageWrap}>{listing.image_url ? <Image source={listing.image_url} contentFit="cover" style={styles.image} /> : <View style={[styles.image, styles.fallback, { backgroundColor: "#F5EBDD" }]}><Text style={[styles.fallbackText, { color: colors.primary }]}>SultraKita</Text></View>}</View><Text style={[styles.price, { color: colors.primary }]}>{typeof listing.price === "number" ? `Rp ${listing.price.toLocaleString("id-ID")}` : "Harga hubungi seller"}</Text><Text style={[styles.title, { color: colors.foreground }]}>{listing.title}</Text><Text style={[styles.meta, { color: colors.muted }]}>{listing.district || listing.city || "Sulawesi Tenggara"} · {listing.seller_name || listing.seller?.name || "Seller lokal"}</Text><View style={[styles.divider, { backgroundColor: colors.border }]} /><Text style={[styles.section, { color: colors.foreground }]}>Tentang listing</Text><Text style={[styles.description, { color: colors.muted }]}>{listing.description || "Seller belum menambahkan deskripsi."}</Text><View style={styles.actions}><Pressable onPress={() => Alert.alert("Chat seller", "Masuk terlebih dahulu untuk memulai percakapan dengan seller.")} style={[styles.primaryButton, { backgroundColor: colors.primary }]}><Text style={styles.primaryText}>Chat seller</Text></Pressable><Pressable onPress={async () => { await AsyncStorage.setItem(`sultra_saved_${id}`, "true"); Alert.alert("Tersimpan", "Listing ini disimpan di perangkatmu."); }} style={[styles.secondaryButton, { borderColor: colors.primary }]}><Text style={[styles.secondaryText, { color: colors.primary }]}>Simpan</Text></Pressable><Pressable onPress={() => Share.share({ message: `${listing.title} — SultraKita` })} style={[styles.secondaryButton, { borderColor: colors.border }]}><Text style={[styles.secondaryText, { color: colors.muted }]}>Bagikan</Text></Pressable></View></> : <View style={styles.empty}><Text style={[styles.title, { color: colors.foreground }]}>{error}</Text><Text style={[styles.meta, { color: colors.muted }]}>Coba kembali ke beranda dan ulangi.</Text></View>}
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 36 }, back: { fontSize: 16, fontWeight: "800", marginBottom: 16 }, imageWrap: { borderRadius: 22, overflow: "hidden" }, image: { width: "100%", height: 280 }, fallback: { alignItems: "center", justifyContent: "center" }, fallbackText: { fontSize: 28, fontWeight: "900" }, price: { fontSize: 18, fontWeight: "900", marginTop: 22 }, title: { fontSize: 28, lineHeight: 34, fontWeight: "800", marginTop: 7 }, meta: { fontSize: 14, lineHeight: 20, marginTop: 8 }, divider: { height: 1, marginVertical: 24 }, section: { fontSize: 18, fontWeight: "800" }, description: { fontSize: 15, lineHeight: 24, marginTop: 10 }, actions: { flexDirection: "row", gap: 10, marginTop: 28 }, primaryButton: { flex: 1, borderRadius: 15, alignItems: "center", paddingVertical: 15 }, primaryText: { color: "#FFFFFF", fontWeight: "800", fontSize: 15 }, secondaryButton: { borderWidth: 1, borderRadius: 15, alignItems: "center", paddingVertical: 15, paddingHorizontal: 18 }, secondaryText: { fontWeight: "800", fontSize: 15 }, empty: { paddingVertical: 80, alignItems: "center" } });
