'use client';

import { Building, Home, MapPin, Plus, RefreshCw, Repeat2, Search, ShieldCheck, Siren, University } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AppLayout } from '@/components/layout/AppLayout';
import { PropertyCard } from '@/components/property/PropertyCard';
import { getProperties } from '@/lib/actions/property';

const categories = [{ key: undefined, label: 'Semua', Icon: Building }, { key: 'rumah_sewa', label: 'Rumah Sewa', Icon: Home }, { key: 'kos_kosan', label: 'Kos-kosan', Icon: University }, { key: 'rumah_takeover', label: 'Takeover', Icon: Repeat2 }, { key: 'lelang', label: 'Lelang', Icon: Siren }, { key: 'rumah_subsidi', label: 'Subsidi', Icon: ShieldCheck }] as const;
export default function PropertiPage() { const [category, setCategory] = useState<(typeof categories)[number]['key']>(); const [district, setDistrict] = useState(''); const [properties, setProperties] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); const result = await getProperties({ category, district: district || undefined }); setProperties(result.ok ? result.data : []); setLoading(false); }
  useEffect(() => { void load(); }, [category, district]);
  return <AppLayout><main className="platform-shell mx-auto max-w-6xl"><header className="mb-5 rounded-3xl bg-gradient-to-br from-sultra-forest via-sultra-teal to-sultra-blue p-6 text-white shadow-lg"><span className="eyebrow text-sultra-sand"><Building size={14}/> SUKI SUITES</span><h1 className="mt-2 text-3xl font-bold">Suki Properti</h1><p className="mt-1 text-white/80">Temukan Hunian Impian di Sultra</p><div className="mt-5 flex gap-2 rounded-2xl bg-white p-2"><Search className="ml-2 mt-2 text-gray-400" size={18}/><input value={district} onChange={event => setDistrict(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') void load(); }} className="min-w-0 flex-1 bg-transparent px-2 py-1 text-sm text-gray-800 outline-none" placeholder="Cari berdasarkan distrik, misalnya Kendari..." aria-label="Cari distrik properti"/><button onClick={() => void load()} className="rounded-xl bg-sultra-teal px-4 py-2 text-sm font-semibold text-white">Cari</button></div></header><div className="mb-6 flex gap-2 overflow-x-auto pb-2">{categories.map(({ key, label, Icon }) => <button key={label} onClick={() => setCategory(key)} className={`flex shrink-0 items-center gap-2 rounded-full px-4 py-2 text-sm transition ${category === key ? 'bg-sultra-teal text-white' : 'bg-sultra-mint text-sultra-forest'}`}><Icon size={16}/>{label}</button>)}</div>{loading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="h-72 animate-pulse rounded-2xl bg-sultra-mint/60"/><div className="h-72 animate-pulse rounded-2xl bg-sultra-mint/60"/><div className="h-72 animate-pulse rounded-2xl bg-sultra-mint/60"/></div> : properties.length ? <div className="grid grid-cols-2 gap-4 lg:grid-cols-3">{properties.map(property => <PropertyCard key={property.id} property={property}/>)}</div> : <div className="rounded-2xl border border-dashed border-sultra-mint p-10 text-center"><MapPin className="mx-auto text-sultra-teal"/><p className="mt-3 font-semibold text-sultra-forest">Belum ada properti yang cocok.</p><p className="mt-1 text-sm text-gray-500">Jadilah yang pertama memasang hunian di distrik ini.</p><button onClick={() => void load()} className="mt-4 text-sm text-sultra-teal"><RefreshCw size={14} className="mr-1 inline"/>Muat ulang</button></div>}<Link href="/properti/create" className="fixed bottom-20 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-sultra-gold text-sultra-forest shadow-xl transition hover:scale-105 md:bottom-8" aria-label="Pasang Properti"><Plus size={25}/></Link></main></AppLayout>; }
