'use client';

import { ArrowLeft, Check, Clock3, MessageSquare } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { AppLayout } from '@/components/layout/AppLayout';
import { getSupportTicket } from '@/lib/actions/support';
import { TicketStatusBadge, type TicketStatus } from '@/components/support/SupportComponents';
export default function TicketDetailPage(){const params=useParams<{id:string}>();const [ticket,setTicket]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{if(params.id)getSupportTicket(params.id).then(response=>{if(response.ok)setTicket(response.data);else setError(response.error)});},[params.id]);return <AppLayout><main className="platform-shell mx-auto max-w-3xl"><Link href="/support" className="mb-4 inline-flex items-center gap-2 text-sm text-sultra-teal"><ArrowLeft size={16}/> Laporkan Masalah</Link>{error?<div className="rounded-2xl bg-red-50 p-5 text-red-700">{error}</div>:!ticket?<div className="h-48 animate-pulse rounded-2xl bg-sultra-mint/60"/>:<div className="space-y-5"><header className="rounded-3xl bg-gradient-to-br from-sultra-forest to-sultra-teal p-6 text-white"><p className="font-mono text-sm text-sultra-sand">{ticket.ticket_number}</p><h1 className="mt-2 text-2xl font-bold">{ticket.subject}</h1><div className="mt-4"><TicketStatusBadge status={ticket.status as TicketStatus}/></div></header><section className="rounded-2xl border border-sultra-mint bg-white p-5 dark:bg-sultra-dark"><h2 className="font-bold">Progress ticket</h2><div className="mt-5 space-y-4">{['Ticket dibuat','Diterima admin','Sedang diproses','Selesai'].map((label,index)=>{const complete=(ticket.status==='resolved'||ticket.status==='closed')|| (ticket.status==='in_progress'&&index<3)||(ticket.status==='open'&&index<2);return <div key={label} className="flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-full ${complete?'bg-sultra-teal text-white':'bg-gray-100 text-gray-400'}`}>{complete?<Check size={16}/>:<Clock3 size={16}/>}</span><span className={complete?'font-semibold':'text-gray-400'}>{label}</span></div>})}</div></section><section className="rounded-2xl border border-sultra-mint bg-white p-5 dark:bg-sultra-dark"><h2 className="flex items-center gap-2 font-bold"><MessageSquare size={18} className="text-sultra-teal"/> Percakapan</h2><p className="mt-4 whitespace-pre-wrap text-sm text-gray-700 dark:text-sultra-sand">{ticket.description}</p>{ticket.admin_response&&<div className="mt-4 rounded-xl bg-sultra-mint/50 p-4 text-sm"><b>Respons support:</b><p className="mt-1">{ticket.admin_response}</p></div>}</section></div>}</main></AppLayout>}
