'use client';

import { Bell, Check, Circle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AppLayout } from '@/components/layout/AppLayout';
import { supabase } from '@/lib/supabase/client';

type Notification = { id: string; title: string; body: string | null; is_read: boolean; created_at: string };
export default function NotificationsPage() { const [items, setItems] = useState<Notification[]>([]); useEffect(() => { let active = true; async function load() { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from('notifications').select('id,title,body,is_read,created_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(50); if (active) setItems((data || []) as Notification[]); } void load(); if (!supabase) return () => { active = false; }; const channel = supabase.channel('notifications-page').on('postgres_changes', { event: '*', schema: 'public', table: 'notifications' }, () => void load()).subscribe(); return () => { active = false; void supabase?.removeChannel(channel); }; }, []); async function markRead(id: string) { if (!supabase) return; await supabase.from('notifications').update({ is_read: true }).eq('id', id); setItems(current => current.map(item => item.id === id ? { ...item, is_read: true } : item)); }
  return <AppLayout><main className="platform-shell mx-auto max-w-3xl"><header className="mb-6 rounded-3xl bg-gradient-to-br from-sultra-forest to-sultra-teal p-6 text-white"><span className="eyebrow text-sultra-sand"><Bell size={14}/> PUSAT AKTIVITAS</span><h1 className="mt-2 text-3xl font-bold">Notifikasi</h1><p className="mt-1 text-white/80">Update terbaru dari aktivitas akun dan komunitasmu.</p></header><div className="space-y-2">{items.length ? items.map(item => <article key={item.id} className={`flex gap-3 rounded-2xl border p-4 transition ${item.is_read ? 'border-gray-100 bg-white dark:bg-sultra-dark' : 'border-sultra-mint bg-sultra-mint/30'}`}><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-sultra-teal text-white"><Bell size={18}/></div><div className="min-w-0 flex-1"><h2 className="font-semibold">{item.title}</h2>{item.body && <p className="mt-1 text-sm text-gray-600 dark:text-sultra-sand/80">{item.body}</p>}<time className="mt-2 block text-xs text-gray-500">{new Date(item.created_at).toLocaleString('id-ID')}</time></div>{item.is_read ? <Check className="text-sultra-teal" size={18}/> : <button onClick={() => void markRead(item.id)} className="text-sultra-teal" aria-label="Tandai sudah dibaca"><Circle size={15}/></button>}</article>) : <div className="rounded-2xl border border-dashed border-sultra-mint p-10 text-center text-gray-500">Belum ada notifikasi baru.</div>}</div></main></AppLayout>; }
