'use client';

import { Globe2, Heart, MessageCircle, MoreHorizontal, Share2 } from 'lucide-react';
import { useState } from 'react';

type FeedPostProps = { author: string; avatar?: string; time: string; location?: string; caption: string; imageUrl?: string; imageLabel?: string; likes?: number; comments?: number; onFollow?: () => void; onComment?: () => void; onShare?: () => void };
export function FeedPost({ author, avatar, time, location, caption, imageUrl, imageLabel, likes = 0, comments = 0, onFollow, onComment, onShare }: FeedPostProps) {
  const [liked, setLiked] = useState(false);
  const initials = avatar || author.split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase();
  return <article className="mb-4 overflow-hidden rounded-xl bg-white shadow-sm dark:bg-sultra-dark"><header className="flex items-start gap-3 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-full bg-sultra-teal text-xs font-semibold text-white">{initials}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="truncate text-sm text-gray-900 dark:text-sultra-sand">{author}</strong><button onClick={onFollow} className="text-xs font-medium text-sultra-teal">Ikuti</button></div><span className="flex items-center gap-1 text-[11px] text-gray-500 dark:text-sultra-sand/60">{time}{location && ` · ${location}`} · <Globe2 size={11}/></span></div><button className="rounded-full p-1 text-gray-500 hover:bg-gray-100 dark:hover:bg-sultra-forest/20" aria-label="Opsi postingan"><MoreHorizontal size={19}/></button></header><p className="px-4 pb-3 text-sm leading-6 text-gray-800 dark:text-sultra-sand">{caption}</p>{imageUrl ? <img src={imageUrl} alt={imageLabel || ''} className="max-h-[520px] w-full object-cover"/> : imageLabel && <div className="grid aspect-[16/9] place-items-center bg-gradient-to-br from-sultra-teal to-sultra-forest text-2xl font-bold tracking-[.25em] text-white">{imageLabel}</div>}<div className="flex items-center justify-between px-4 py-2 text-xs text-gray-500 dark:text-sultra-sand/60"><span><Heart size={14} className="mr-1 inline fill-sultra-coral text-sultra-coral"/> {likes + (liked ? 1 : 0)}</span><span>{comments} komentar</span></div><div className="mx-4 border-t border-gray-100 dark:border-sultra-forest/30"/><div className="grid grid-cols-3 gap-1 p-1"><button onClick={() => setLiked(value => !value)} className={`flex items-center justify-center gap-2 rounded-lg py-2 text-xs transition-colors hover:bg-gray-100 dark:hover:bg-sultra-forest/20 ${liked ? 'font-semibold text-sultra-coral' : 'text-gray-600 dark:text-sultra-mint'}`}><Heart size={16} fill={liked ? 'currentColor' : 'none'}/> Suka</button><button onClick={onComment} className="flex items-center justify-center gap-2 rounded-lg py-2 text-xs text-gray-600 transition-colors hover:bg-gray-100 dark:text-sultra-mint dark:hover:bg-sultra-forest/20"><MessageCircle size={16}/> Komentar</button><button onClick={onShare} className="flex items-center justify-center gap-2 rounded-lg py-2 text-xs text-gray-600 transition-colors hover:bg-gray-100 dark:text-sultra-mint dark:hover:bg-sultra-forest/20"><Share2 size={16}/> Bagikan</button></div></article>;
}
