'use client';

import { Bookmark, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AppLayout } from '@/components/layout/AppLayout';
import { supabase } from '@/lib/supabase/client';

type Saved = { id: string; item_type: string; item_id: string; metadata: Record<string, unknown> | null; created_at: string };
export default function SavedPage() { const [items, setItems] = useState<Saved[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { let active = true; async function load() { if (!supabase) { setLoading(false); return; } const { data: { user } } = await supabase.auth.getUser(); if (!user) { setLoading(false); return; } const { data } = await supabase.from('saved_items').select('id,item_type,item_id,metadata,created_at').eq('user_id', user.id).order('created_at', { ascending: false }); if (active) { setItems((data || []) as Saved[]); setLoading(false); } } void load(); return () => { active = false; }; }, []); async function remove(id: string) { if (!supabase) return; await supabase.from('saved_items').delete().eq('id', id); setItems(current => current.filter(item => item.id !== id)); }
  return <AppLayout><main className="platform-shell mx-auto max-w-5xl"><header className="mb-6 rounded-3xl bg-gradient-to-br from-sultra-forest to-sultra-teal p-6 text-white"><span className="eyebrow text-sultra-sand"><Bookmark size={14}/> KOLEKSI PRIBADI</span><h1 className="mt-2 text-3xl font-bold">Tersimpan</h1><p className="mt-1 text-white/80">Listing, Reels, dan postingan yang ingin kamu kunjungi lagi.</p></header>{loading ? <div className="h-40 animate-pulse rounded-2xl bg-sultra-mint/60"/> : items.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(item => <article key={item.id} className="rounded-2xl border border-sultra-mint bg-white p-4 shadow-sm dark:bg-sultra-dark"><div className="grid h-28 place-items-center rounded-xl bg-sultra-mint/60 text-sultra-teal"><Bookmark size={28}/></div><p className="mt-3 text-xs font-semibold uppercase text-sultra-teal">{item.item_type}</p><h2 className="mt-1 line-clamp-2 font-semibold">{String(item.metadata?.title || `Item ${item.item_id.slice(0, 8)}`)}</h2><button onClick={() => void remove(item.id)} className="mt-4 flex items-center gap-2 text-sm text-red-600"><Trash2 size={15}/> Hapus dari Tersimpan</button></article>)}</div> : <div className="rounded-2xl border border-dashed border-sultra-mint p-10 text-center text-gray-500">Belum ada item tersimpan.</div>}</main></AppLayout>; }
