INSERT INTO external_jobs (external_id, source, source_label, title, company, city, province, category, employment_type, salary_text, description, url, image_url, posted_at, expires_at, observed_at, provenance, raw_json)
VALUES
('https://id.jobstreet.com/id/jobs/in-Kendari-Sulawesi-Tenggara', 'job-url:id.jobstreet.com', 'JobStreet Indonesia', 'Lowongan kerja Kendari — JobStreet', 'JobStreet Indonesia', 'Kendari', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman pencarian lowongan kerja untuk Kendari dan sekitarnya. Buka sumber asli untuk melihat posisi, persyaratan, dan cara melamar terbaru.', 'https://id.jobstreet.com/id/jobs/in-Kendari-Sulawesi-Tenggara', 'https://id.jobstreet.com/favicon.ico', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb),
('https://id.jobstreet.com/id/jobs/in-Sulawesi-Tenggara', 'job-url:id.jobstreet.com', 'JobStreet Indonesia', 'Lowongan kerja Sulawesi Tenggara — JobStreet', 'JobStreet Indonesia', 'Sulawesi Tenggara', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman pencarian lowongan kerja untuk wilayah Sulawesi Tenggara. Buka sumber asli untuk melihat posisi, persyaratan, dan cara melamar terbaru.', 'https://id.jobstreet.com/id/jobs/in-Sulawesi-Tenggara', 'https://id.jobstreet.com/favicon.ico', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb),
('https://id.jora.com/lowongan-di-Kendari-Sulawesi-Tenggara', 'job-url:id.jora.com', 'Jora Indonesia', 'Lowongan kerja Kendari, Sulawesi Tenggara — Jora', 'Jora Indonesia', 'Kendari', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman agregasi lowongan kerja Kendari dan Sulawesi Tenggara. Detail, waktu tayang, dan ketersediaan posisi harus diperiksa di sumber asli.', 'https://id.jora.com/lowongan-di-Kendari-Sulawesi-Tenggara', 'https://id.jora.com/jora-social-sharing-banner.png', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb),
('https://id.jora.com/lowongan-kendari', 'job-url:id.jora.com', 'Jora Indonesia', 'Lowongan kerja Kendari — Jora', 'Jora Indonesia', 'Kendari', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman pencarian Jora untuk lowongan di Kendari. Buka sumber asli untuk memeriksa detail dan status lamaran.', 'https://id.jora.com/lowongan-kendari', 'https://id.jora.com/jora-social-sharing-banner.png', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb),
('https://id.jora.com/lowongan-PT-di-Kendari-Sulawesi-Tenggara', 'job-url:id.jora.com', 'Jora Indonesia', 'Lowongan PT di Kendari — Jora', 'Jora Indonesia', 'Kendari', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman pencarian Jora untuk lowongan perusahaan/PT di Kendari dan Sulawesi Tenggara. Detail harus diverifikasi di sumber asli.', 'https://id.jora.com/lowongan-PT-di-Kendari-Sulawesi-Tenggara', 'https://id.jora.com/jora-social-sharing-banner.png', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb),
('https://id.indeed.com/jobs?l=kendari', 'job-url:id.indeed.com', 'Indeed Indonesia', 'Lowongan kerja Kendari — Indeed', 'Indeed Indonesia', 'Kendari', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman pencarian Indeed untuk pekerjaan di Kendari. Buka sumber asli untuk melihat detail, persyaratan, dan tombol melamar.', 'https://id.indeed.com/jobs?l=kendari', 'https://id.indeed.com/favicon.ico', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb),
('https://id.indeed.com/lowongan-kerja-Loker-Kendari-di-Kendari', 'job-url:id.indeed.com', 'Indeed Indonesia', 'Loker Kendari — Indeed', 'Indeed Indonesia', 'Kendari', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman pencarian Indeed untuk kata kunci loker Kendari. Status dan detail posisi dapat berubah; periksa sumber asli sebelum melamar.', 'https://id.indeed.com/lowongan-kerja-Loker-Kendari-di-Kendari', 'https://id.indeed.com/favicon.ico', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb),
('https://loker.my.id/jobs/kota/kendari', 'job-url:loker.my.id', 'Loker.my.id', 'Lowongan Kerja Kendari — Loker.my.id', 'Loker.my.id', 'Kendari', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman daftar lowongan kerja Kendari dari Loker.my.id. Buka sumber asli untuk melihat perusahaan, syarat, dan cara melamar.', 'https://loker.my.id/jobs/kota/kendari', 'https://loker.my.id/favicon.ico', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb),
('https://id.jobstreet.com/id/loker-jobs/in-Kendari-Sulawesi-Tenggara', 'job-url:id.jobstreet.com', 'JobStreet Indonesia', 'Pencarian Loker Kendari — JobStreet', 'JobStreet Indonesia', 'Kendari', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman pencarian JobStreet dengan kata kunci loker untuk Kendari. Buka sumber asli untuk hasil terbaru.', 'https://id.jobstreet.com/id/loker-jobs/in-Kendari-Sulawesi-Tenggara', 'https://id.jobstreet.com/favicon.ico', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb),
('https://id.jobstreet.com/id/semua-jobs/in-Kendari-Sulawesi-Tenggara', 'job-url:id.jobstreet.com', 'JobStreet Indonesia', 'Semua pekerjaan Kendari — JobStreet', 'JobStreet Indonesia', 'Kendari', 'Sulawesi Tenggara', 'Lowongan Kerja', 'Lihat sumber', '', 'Halaman JobStreet untuk seluruh hasil pekerjaan di Kendari dan sekitarnya. Buka sumber asli untuk posisi dan status terbaru.', 'https://id.jobstreet.com/id/semua-jobs/in-Kendari-Sulawesi-Tenggara', 'https://id.jobstreet.com/favicon.ico', NULL, NULL, now(), 'user_submitted_public_metadata', '{"seed":true,"source_type":"url_card"}'::jsonb)
ON CONFLICT (source, external_id) DO UPDATE SET source_label = EXCLUDED.source_label, title = EXCLUDED.title, company = EXCLUDED.company, city = EXCLUDED.city, province = EXCLUDED.province, category = EXCLUDED.category, description = EXCLUDED.description, url = EXCLUDED.url, image_url = EXCLUDED.image_url, observed_at = now(), provenance = EXCLUDED.provenance, raw_json = EXCLUDED.raw_json;
