import type { LanguageCode } from '@/lib/preferences';

type Labels = { settings: string; privacy: string; language: string; darkMode: string; lightMode: string; active: string; chooseLanguage: string; system: string; premium: string; logout: string };
const labels: Record<LanguageCode, Labels> = {
  id: { settings: 'Pengaturan', privacy: 'Pusat Privasi', language: 'Bahasa', darkMode: 'Mode gelap', lightMode: 'Mode terang', active: 'Aktif', chooseLanguage: 'Pilih bahasa', system: 'Ikuti perangkat', premium: 'SultraKita Premium', logout: 'Keluar' },
  en: { settings: 'Settings', privacy: 'Privacy Center', language: 'Language', darkMode: 'Dark mode', lightMode: 'Light mode', active: 'Active', chooseLanguage: 'Choose language', system: 'Follow device', premium: 'SultraKita Premium', logout: 'Log out' },
  ms: { settings: 'Tetapan', privacy: 'Pusat Privasi', language: 'Bahasa', darkMode: 'Mod gelap', lightMode: 'Mod cerah', active: 'Aktif', chooseLanguage: 'Pilih bahasa', system: 'Ikut peranti', premium: 'SultraKita Premium', logout: 'Log keluar' },
  jv: { settings: 'Setelan', privacy: 'Pusat Privasi', language: 'Basa', darkMode: 'Mode peteng', lightMode: 'Mode padhang', active: 'Aktif', chooseLanguage: 'Pilih basa', system: 'Miturut piranti', premium: 'SultraKita Premium', logout: 'Metu' },
  su: { settings: 'Pangaturan', privacy: 'Puseur Privasi', language: 'Basa', darkMode: 'Mode poék', lightMode: 'Mode caang', active: 'Aktip', chooseLanguage: 'Pilih basa', system: 'Tuturkeun alat', premium: 'SultraKita Premium', logout: 'Kaluar' },
  zh: { settings: '设置', privacy: '隐私中心', language: '语言', darkMode: '深色模式', lightMode: '浅色模式', active: '在线', chooseLanguage: '选择语言', system: '跟随设备', premium: 'SultraKita Premium', logout: '退出' },
  ja: { settings: '設定', privacy: 'プライバシーセンター', language: '言語', darkMode: 'ダークモード', lightMode: 'ライトモード', active: 'オンライン', chooseLanguage: '言語を選択', system: '端末に合わせる', premium: 'SultraKita Premium', logout: 'ログアウト' },
  ko: { settings: '설정', privacy: '개인정보 보호 센터', language: '언어', darkMode: '다크 모드', lightMode: '라이트 모드', active: '활성', chooseLanguage: '언어 선택', system: '기기 설정 따르기', premium: 'SultraKita Premium', logout: '로그아웃' },
  ar: { settings: 'الإعدادات', privacy: 'مركز الخصوصية', language: 'اللغة', darkMode: 'الوضع الداكن', lightMode: 'الوضع الفاتح', active: 'نشط', chooseLanguage: 'اختر اللغة', system: 'اتباع الجهاز', premium: 'SultraKita Premium', logout: 'تسجيل الخروج' },
  hi: { settings: 'सेटिंग', privacy: 'गोपनीयता केंद्र', language: 'भाषा', darkMode: 'डार्क मोड', lightMode: 'लाइट मोड', active: 'सक्रिय', chooseLanguage: 'भाषा चुनें', system: 'डिवाइस के अनुसार', premium: 'SultraKita Premium', logout: 'लॉग आउट' },
  es: { settings: 'Configuración', privacy: 'Centro de privacidad', language: 'Idioma', darkMode: 'Modo oscuro', lightMode: 'Modo claro', active: 'Activo', chooseLanguage: 'Elegir idioma', system: 'Seguir dispositivo', premium: 'SultraKita Premium', logout: 'Cerrar sesión' },
  fr: { settings: 'Paramètres', privacy: 'Centre de confidentialité', language: 'Langue', darkMode: 'Mode sombre', lightMode: 'Mode clair', active: 'Actif', chooseLanguage: 'Choisir une langue', system: 'Suivre l’appareil', premium: 'SultraKita Premium', logout: 'Se déconnecter' },
  de: { settings: 'Einstellungen', privacy: 'Datenschutzzentrum', language: 'Sprache', darkMode: 'Dunkelmodus', lightMode: 'Heller Modus', active: 'Aktiv', chooseLanguage: 'Sprache wählen', system: 'Gerät folgen', premium: 'SultraKita Premium', logout: 'Abmelden' },
  pt: { settings: 'Configurações', privacy: 'Central de privacidade', language: 'Idioma', darkMode: 'Modo escuro', lightMode: 'Modo claro', active: 'Ativo', chooseLanguage: 'Escolher idioma', system: 'Seguir dispositivo', premium: 'SultraKita Premium', logout: 'Sair' },
  it: { settings: 'Impostazioni', privacy: 'Centro privacy', language: 'Lingua', darkMode: 'Modalità scura', lightMode: 'Modalità chiara', active: 'Attivo', chooseLanguage: 'Scegli lingua', system: 'Segui dispositivo', premium: 'SultraKita Premium', logout: 'Esci' },
  nl: { settings: 'Instellingen', privacy: 'Privacycentrum', language: 'Taal', darkMode: 'Donkere modus', lightMode: 'Lichte modus', active: 'Actief', chooseLanguage: 'Kies taal', system: 'Apparaat volgen', premium: 'SultraKita Premium', logout: 'Uitloggen' },
  ru: { settings: 'Настройки', privacy: 'Центр конфиденциальности', language: 'Язык', darkMode: 'Тёмная тема', lightMode: 'Светлая тема', active: 'Активен', chooseLanguage: 'Выберите язык', system: 'Как на устройстве', premium: 'SultraKita Premium', logout: 'Выйти' },
  tr: { settings: 'Ayarlar', privacy: 'Gizlilik Merkezi', language: 'Dil', darkMode: 'Koyu mod', lightMode: 'Açık mod', active: 'Aktif', chooseLanguage: 'Dil seçin', system: 'Cihazı takip et', premium: 'SultraKita Premium', logout: 'Çıkış yap' },
  th: { settings: 'การตั้งค่า', privacy: 'ศูนย์ความเป็นส่วนตัว', language: 'ภาษา', darkMode: 'โหมดมืด', lightMode: 'โหมดสว่าง', active: 'ใช้งานอยู่', chooseLanguage: 'เลือกภาษา', system: 'ตามอุปกรณ์', premium: 'SultraKita Premium', logout: 'ออกจากระบบ' },
  vi: { settings: 'Cài đặt', privacy: 'Trung tâm quyền riêng tư', language: 'Ngôn ngữ', darkMode: 'Chế độ tối', lightMode: 'Chế độ sáng', active: 'Đang hoạt động', chooseLanguage: 'Chọn ngôn ngữ', system: 'Theo thiết bị', premium: 'SultraKita Premium', logout: 'Đăng xuất' },
  fil: { settings: 'Mga setting', privacy: 'Privacy Center', language: 'Wika', darkMode: 'Dark mode', lightMode: 'Light mode', active: 'Aktibo', chooseLanguage: 'Pumili ng wika', system: 'Sundin ang device', premium: 'SultraKita Premium', logout: 'Mag-log out' },
  sw: { settings: 'Mipangilio', privacy: 'Kituo cha Faragha', language: 'Lugha', darkMode: 'Hali nyeusi', lightMode: 'Hali angavu', active: 'Inatumika', chooseLanguage: 'Chagua lugha', system: 'Fuata kifaa', premium: 'SultraKita Premium', logout: 'Toka' },
  bn: { settings: 'সেটিংস', privacy: 'গোপনীয়তা কেন্দ্র', language: 'ভাষা', darkMode: 'ডার্ক মোড', lightMode: 'লাইট মোড', active: 'সক্রিয়', chooseLanguage: 'ভাষা বেছে নিন', system: 'ডিভাইস অনুসরণ করুন', premium: 'SultraKita Premium', logout: 'লগ আউট' },
  ur: { settings: 'ترتیبات', privacy: 'رازداری مرکز', language: 'زبان', darkMode: 'ڈارک موڈ', lightMode: 'لائٹ موڈ', active: 'فعال', chooseLanguage: 'زبان منتخب کریں', system: 'ڈیوائس کی پیروی کریں', premium: 'SultraKita Premium', logout: 'لاگ آؤٹ' },
};
export function getLabels(language: LanguageCode) { return labels[language] || labels.id; }
