'use client';

import { Hash, Store, Users } from 'lucide-react';

type RightSidebarProps = { onMarketplace?: () => void; onGroups?: () => void };
const listings = ['Kain Tenun Buton Premium', 'Paket Ikan Bakar Sambal', 'Paket Snorkeling Wakatobi'];
const groups = ['Jual Beli Kendari & Sekitarnya', 'Pecinta Wisata Wakatobi', 'UMKM Sultra Naik Kelas'];
export function RightSidebar({ onMarketplace, onGroups }: RightSidebarProps) {
  return <aside className="hidden lg:block lg:w-72 lg:shrink-0" aria-label="Informasi SultraKita"><div className="sticky top-32 space-y-4 p-4"><section className="rounded-xl bg-white p-4 shadow-sm dark:bg-sultra-dark"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold text-sultra-forest dark:text-sultra-mint">Marketplace pilihan</h2><Store size={17} className="text-sultra-teal"/></div><div className="space-y-3">{listings.map((listing, index) => <button key={listing} onClick={onMarketplace} className="flex w-full items-center gap-3 text-left hover:text-sultra-teal"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg text-xs font-bold ${['bg-sultra-gold/30 text-sultra-forest', 'bg-sultra-teal/20 text-sultra-teal', 'bg-blue-100 text-blue-700'][index]}`}>{index + 1}</span><span className="min-w-0"><strong className="block truncate text-xs">{listing}</strong><small className="text-[10px] text-gray-500">Seller terverifikasi</small></span></button>)}</div><button onClick={onMarketplace} className="mt-3 text-xs font-medium text-sultra-teal">Lihat semua listing</button></section><section className="rounded-xl bg-white p-4 shadow-sm dark:bg-sultra-dark"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold text-sultra-forest dark:text-sultra-mint">Komunitas untukmu</h2><Users size={17} className="text-sultra-teal"/></div><div className="space-y-2">{groups.map(group => <button key={group} onClick={onGroups} className="block w-full truncate rounded-lg px-2 py-2 text-left text-xs hover:bg-sultra-mint/30">{group}</button>)}</div></section><section className="rounded-xl bg-white p-4 shadow-sm dark:bg-sultra-dark"><h2 className="mb-3 text-sm font-semibold text-sultra-forest dark:text-sultra-mint">Trending di Sultra</h2><div className="space-y-2">{['#Wakatobi', '#UMKMSultra', '#KulinerKendari'].map(tag => <div key={tag} className="flex items-center gap-2 text-xs text-gray-600 dark:text-sultra-sand/70"><Hash size={14} className="text-sultra-teal"/>{tag}</div>)}</div></section></div></aside>;
}
