'use client';

import { Heart, Share2, Volume2, VolumeX } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import type { ReelRecord } from '@/lib/actions/reels';
import { usePreferences } from '@/lib/preferences';
import { dictChatNews } from '@/lib/i18n/dict-chatnews';
export type DisplayReel = ReelRecord & { author?: string; title?: string; description?: string; avatar?: string; likes?: number; comments?: number };
export function ReelCard({ reel, onLike }: { reel: DisplayReel; onLike?: () => void }) {
  const { language } = usePreferences();
  const t = dictChatNews[language] ?? dictChatNews.id;
  const ref = useRef<HTMLElement>(null); const videoRef = useRef<HTMLVideoElement>(null); const [active, setActive] = useState(false); const [muted, setMuted] = useState(true); const [liked, setLiked] = useState(false); useEffect(() => { const element = ref.current; if (!element) return; const observer = new IntersectionObserver(([entry]) => setActive(entry.isIntersecting && entry.intersectionRatio >= .65), { threshold: [.2, .65, .9] }); observer.observe(element); return () => observer.disconnect(); }, []); useEffect(() => { const video = videoRef.current; if (!video) return; if (active) video.play().catch(() => undefined); else video.pause(); }, [active]); function like() { setLiked(value => !value); onLike?.(); } return <article ref={ref} className="reel-snap-card"><div className="reel-video-wrap"><video ref={videoRef} src={reel.video_url} poster={reel.thumbnail_url || undefined} muted={muted} loop playsInline preload="metadata"/><button className="reel-mute" onClick={() => setMuted(value => !value)} aria-label={muted ? t.reelUnmute : t.reelMute}>{muted ? <VolumeX size={18}/> : <Volume2 size={18}/>}</button><div className="reel-overlay"><div className="reel-caption"><strong>{reel.author || t.reelDefaultAuthor}</strong><p>{reel.caption || reel.title || t.reelDefaultCaption}</p>{reel.district && <small>📍 {reel.district}</small>}</div><div className="reel-side-actions"><button className={liked ? 'active' : ''} onClick={like} aria-label={t.reelLike}><Heart size={21} fill={liked ? 'currentColor' : 'none'}/><small>{(reel.likes_count || reel.likes || 0) + (liked ? 1 : 0)}</small></button><button onClick={() => navigator.clipboard?.writeText(window.location.href)} aria-label={t.reelShare}><Share2 size={21}/><small>{t.reelShare}</small></button></div></div></div></article>; }
