'use client';

import Link from 'next/link';
import { ArrowLeft, Save } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { AppLayout } from '@/components/layout/AppLayout';
import { getMyProperty, updateProperty } from '@/lib/actions/property';

export default function EditSellerPropertyPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const [form, setForm] = useState({ title: '', description: '', price: '', priceType: 'total', status: 'available' });
  const [message, setMessage] = useState('');
  const [saving, setSaving] = useState(false);
  useEffect(() => { void getMyProperty(params.id).then(response => { if (response.ok && response.data) setForm({ title: response.data.title || '', description: response.data.description || '', price: String(response.data.price || ''), priceType: response.data.price_type || 'total', status: response.data.status || 'available' }); else setMessage(response.ok ? 'Properti tidak ditemukan.' : response.error); }); }, [params.id]);
  async function save() { setSaving(true); setMessage(''); const response = await updateProperty(params.id, { title: form.title, description: form.description, price: Number(form.price), priceType: form.priceType as 'per_bulan'|'per_tahun'|'total'|'mulai_dari'|'nego', status: form.status as 'draft'|'pending_review'|'available'|'rented'|'sold'|'archived'|'rejected' }); setSaving(false); if (!response.ok) { setMessage(response.error); return; } router.push('/dashboard/properties'); }
  return <AppLayout><main className="platform-shell mx-auto max-w-3xl"><Link href="/dashboard/properties" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-sultra-teal"><ArrowLeft size={16}/> Kembali ke properti saya</Link><section className="rounded-3xl border border-sultra-mint bg-white p-6 shadow-sm dark:bg-sultra-dark"><h1 className="text-2xl font-bold text-sultra-forest dark:text-sultra-sand">Edit properti</h1><p className="mt-1 text-sm text-gray-500">Perubahan hanya berlaku untuk listing milik akun yang sedang login.</p><div className="mt-6 grid gap-4"><label className="grid gap-1 text-sm font-semibold">Judul<input value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} className="field-input"/></label><label className="grid gap-1 text-sm font-semibold">Deskripsi<textarea value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} className="field-input min-h-32"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Harga<input type="number" value={form.price} onChange={event => setForm({ ...form, price: event.target.value })} className="field-input"/></label><label className="grid gap-1 text-sm font-semibold">Tipe harga<select value={form.priceType} onChange={event => setForm({ ...form, priceType: event.target.value })} className="field-input"><option value="per_bulan">Per bulan</option><option value="per_tahun">Per tahun</option><option value="total">Total</option><option value="mulai_dari">Mulai dari</option><option value="nego">Nego</option></select></label></div><label className="grid gap-1 text-sm font-semibold">Status<select value={form.status} onChange={event => setForm({ ...form, status: event.target.value })} className="field-input"><option value="available">Aktif</option><option value="rented">Disewa</option><option value="sold">Terjual</option><option value="archived">Diarsipkan</option></select></label>{message && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</p>}<button onClick={() => void save()} disabled={saving} className="inline-flex w-fit items-center gap-2 rounded-xl bg-sultra-forest px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Save size={16}/>{saving ? 'Menyimpan...' : 'Simpan perubahan'}</button></div></section></main></AppLayout>;
}
