const fs = require('node:fs');
const path = require('node:path');
const file = path.join(__dirname, '..', 'server.js');
let source = fs.readFileSync(file, 'utf8');
source = source.replace("const fs = require('node:fs');\n", '');
source = source.replace("app.use((error, _req, res, _next) => { console.error(error); fail(res, 500, 'Terjadi kesalahan pada server'); });", "app.use((error, _req, res, _next) => { console.error(JSON.stringify({ event: 'request_error', message: error.message, code: error.code || null })); if (res.headersSent) return; const status = Number(error.statusCode || error.status) >= 400 ? Number(error.statusCode || error.status) : 500; return fail(res, status, status === 500 ? 'Terjadi kesalahan pada server' : error.message); });");
fs.writeFileSync(file, source);
const robots = `User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /admin\nSitemap: https://sultrakita-platform.vercel.app/sitemap.xml\n`;
fs.writeFileSync(path.join(__dirname, '..', 'public/robots.txt'), robots);
fs.writeFileSync(path.join(__dirname, '..', 'public/sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://sultrakita-platform.vercel.app/</loc><changefreq>daily</changefreq><priority>1.0</priority></url></urlset>\n`);
