const fs = require('node:fs');
const path = require('node:path');
const file = path.join(__dirname, '..', 'server.js');
let source = fs.readFileSync(file, 'utf8');
const marker = "app.get('/api/admin/overview', requireRole('admin'), adminOnly";
const insert = `app.get('/api/admin/feature-flags', requireRole('admin'), adminOnly, async (_req, res, next) => { try { ok(res, await query('SELECT key, enabled, config, updated_at FROM feature_flags ORDER BY key')); } catch (error) { next(error); } });
app.patch('/api/admin/feature-flags/:key', requireRole('admin'), adminOnly, async (req, res, next) => { try { if (!/^[a-z0-9_]{2,60}$/.test(req.params.key) || typeof req.body?.enabled !== 'boolean') return fail(res, 422, 'Feature flag atau enabled belum valid'); const rows = await query('UPDATE feature_flags SET enabled = ?, updated_at = now() WHERE key = ? RETURNING key, enabled, config, updated_at', [req.body.enabled, req.params.key]); if (!rows.length) return fail(res, 404, 'Feature flag tidak ditemukan'); await run('INSERT INTO audit_logs (actor_id, action, entity_type, metadata) VALUES (?, ?, ?, ?::jsonb)', [req.user.id, req.body.enabled ? 'feature_enabled' : 'feature_disabled', 'feature_flag', JSON.stringify({ key: req.params.key })]); ok(res, rows[0]); } catch (error) { next(error); } });
`;
if (!source.includes("app.get('/api/admin/feature-flags'")) source = source.replace(marker, insert + marker);
const seoMarker = "app.get('/listing/:slug-:id'";
if (!source.includes("app.get('/dukung'")) source = source.replace(seoMarker, "app.get('/dukung', (_req, res) => res.redirect(302, '/#dukungan'));\n" + seoMarker);
fs.writeFileSync(file, source);
