'use client';

import { AlertTriangle, Download, Lock, ShieldCheck, Trash2 } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AppLayout } from '@/components/layout/AppLayout';
import { supabase } from '@/lib/supabase/client';
import { SecurityCheckup, DeviceList } from '@/components/support/SupportComponents';
export default function SecurityCenterPage(){const [devices,setDevices]=useState<any[]>([]);useEffect(()=>{async function load(){if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from('trusted_devices').select('id,device_name,last_active_at').eq('user_id',user.id).order('last_active_at',{ascending:false});setDevices(data||[])}void load()},[]);async function remove(id:string){if(!supabase)return;await supabase.from('trusted_devices').delete().eq('id',id);setDevices(current=>current.filter(device=>device.id!==id))}return <AppLayout><main className="platform-shell mx-auto max-w-5xl"><header className="mb-6 rounded-3xl bg-gradient-to-br from-sultra-forest to-sultra-teal p-7 text-white"><span className="eyebrow text-sultra-sand"><ShieldCheck size={14}/> SECURITY CENTER</span><h1 className="mt-3 text-3xl font-bold">Pusat Keamanan</h1><p className="mt-1 text-white/80">Lindungi akun, data, dan transaksi kamu di SultraKita.</p></header><div className="grid gap-5 md:grid-cols-2"><SecurityCheckup/><DeviceList devices={devices} onRemove={remove}/></div><section className="mt-5 rounded-2xl border border-sultra-mint bg-white p-5 dark:bg-sultra-dark"><h2 className="flex items-center gap-2 font-bold"><AlertTriangle className="text-sultra-gold"/> Perlindungan dari penipuan</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-gray-600 dark:text-sultra-sand/80"><li>Jangan pernah mengirim OTP, PIN, atau kata sandi kepada siapa pun.</li><li>Gunakan chat dan metode pembayaran resmi SultraKita.</li><li>Periksa legalitas dan identitas seller sebelum transaksi.</li><li>Waspadai harga yang tidak masuk akal dan permintaan transfer di luar platform.</li></ul><Link href="/support" className="mt-4 inline-flex rounded-xl bg-sultra-teal px-4 py-2 text-sm font-semibold text-white">Laporkan Penipuan</Link></section><section className="mt-5 grid gap-3 sm:grid-cols-3"><button className="soft-btn justify-center"><Lock size={16}/> Pengaturan Privasi</button><button className="soft-btn justify-center"><Download size={16}/> Download Data</button><button className="soft-btn justify-center text-red-600"><Trash2 size={16}/> Hapus Akun</button></section></main></AppLayout>}
