'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { AppLayout } from '@/components/layout/AppLayout';
type PayoutStatus = 'pending' | 'approved' | 'paid' | 'rejected';
type Payout = { id: number; points: number; rupiah_amount: number; status: PayoutStatus; payout_method: string | null; payout_account_masked: string | null; created_at: string; rejection_reason: string | null; payment_reference: string | null };
const statuses: PayoutStatus[] = ['pending', 'approved', 'paid', 'rejected'];
const labels: Record<PayoutStatus, string> = { pending: 'Pending', approved: 'Approved', paid: 'Paid', rejected: 'Rejected' };
const money = (value: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value || 0);
const date = (value: string) => new Date(value).toLocaleString('id-ID');
export default function AdminAffiliateRewardsPage() {
  const [filter, setFilter] = useState<PayoutStatus | 'all'>('pending'); const [items, setItems] = useState<Payout[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<number | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch(`/api/referral?action=payout_queue&status=${filter}`, { cache: 'no-store' }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error || 'Queue payout belum tersedia.'); setItems(body.data || []); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Queue payout belum tersedia.'); } finally { setLoading(false); } }, [filter]);
  useEffect(() => { void load(); }, [load]);
  const counts = useMemo(() => Object.fromEntries(statuses.map(status => [status, filter === status ? items.length : '—'])), [filter, items.length]);
  const transition = async (item: Payout, toStatus: Exclude<PayoutStatus, 'pending'>) => { let note = ''; let paymentReference = ''; if (toStatus === 'rejected') { note = window.prompt('Alasan penolakan wajib diisi:')?.trim() || ''; if (!note) return; } if (toStatus === 'paid') { paymentReference = window.prompt('Masukkan referensi pembayaran:')?.trim() || ''; if (!paymentReference || !window.confirm('Tandai payout ini PAID? Pastikan operator berbeda dari reviewer approval.')) return; } setBusy(item.id); setError(''); setNotice(''); try { const response = await fetch('/api/referral', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'payout_transition', redemption_id: item.id, to_status: toStatus, note, payment_reference: paymentReference }) }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error || 'Transisi payout gagal.'); setNotice(`Payout #${item.id} berpindah ke status ${labels[toStatus]}.`); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Transisi payout gagal.'); } finally { setBusy(null); } };
  return <AppLayout><main className="platform-shell mx-auto max-w-6xl"><header className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><span className="eyebrow text-sultra-teal">ADMIN · AFFILIATE REWARDS</span><h1 className="mt-2 text-3xl font-bold text-sultra-forest">Payout Operations</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Queue payout dengan transisi terkontrol, akun tetap dimasking, dan seluruh perubahan dicatat pada audit trail.</p></div><span className="rounded-full border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700">MANUAL REVIEW · TWO-PERSON PAY</span></header>
    <section className="grid gap-4 md:grid-cols-4" aria-label="Payout status summary">{statuses.map(status => <article key={status} className="rounded-2xl border border-sultra-mint bg-white p-5"><span className="text-xs font-bold text-slate-500">{labels[status]}</span><strong className="mt-2 block text-2xl text-sultra-forest">{counts[status]}</strong><small className="mt-1 block text-xs text-slate-500">Filter queue aktif</small></article>)}</section>
    <section className="mt-6 rounded-2xl border border-sultra-mint bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="eyebrow text-sultra-teal">PAYOUT QUEUE</span><h2 className="mt-2 text-xl font-bold text-sultra-forest">Review dan rekonsiliasi</h2></div><button className="soft-btn" onClick={() => void load()} disabled={loading}>{loading ? 'Memuat…' : 'Refresh'}</button></div><div className="mt-5 flex gap-2 overflow-x-auto" role="tablist" aria-label="Filter status payout">{[...statuses, 'all' as const].map(status => <button key={status} className={`soft-btn whitespace-nowrap ${filter === status ? 'ring-2 ring-sultra-gold' : ''}`} onClick={() => setFilter(status)}>{status === 'all' ? 'Semua' : labels[status]}</button>)}</div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}{notice && <p className="mt-4 rounded-xl bg-sultra-mint/40 p-3 text-sm text-sultra-forest" role="status">{notice}</p>}<div className="mt-5 grid gap-4">{loading ? <p className="p-8 text-center text-sm text-slate-500">Memuat queue payout…</p> : items.length ? items.map(item => <article key={item.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-sultra-teal">Payout #{item.id} · {labels[item.status]}</p><h3 className="mt-1 text-lg font-bold text-sultra-forest">{money(item.rupiah_amount)}</h3><p className="mt-1 text-xs text-slate-500">{item.points.toLocaleString('id-ID')} star · dibuat {date(item.created_at)}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-600">{item.payout_method || 'Metode tidak tersedia'} · {item.payout_account_masked || 'masked'}</span></div><div className="mt-4 flex flex-wrap gap-2">{item.status === 'pending' && <><button className="soft-btn" disabled={busy === item.id} onClick={() => void transition(item, 'approved')}>Approve</button><button className="rounded-xl border border-red-200 px-4 py-2 text-xs font-bold text-red-700 disabled:opacity-50" disabled={busy === item.id} onClick={() => void transition(item, 'rejected')}>Reject</button></>}{item.status === 'approved' && <button className="rounded-xl bg-sultra-teal px-4 py-2 text-xs font-bold text-white disabled:opacity-50" disabled={busy === item.id} onClick={() => void transition(item, 'paid')}>Mark paid</button>}</div>{item.rejection_reason && <p className="mt-3 text-xs text-red-700">Alasan: {item.rejection_reason}</p>}{item.payment_reference && <p className="mt-3 text-xs text-slate-500">Referensi pembayaran: {item.payment_reference}</p>}</article>) : <div className="rounded-2xl border border-dashed border-sultra-mint p-12 text-center text-sm text-slate-500">Tidak ada payout pada filter ini.</div>}</div></section>
    <section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-bold text-amber-900">Guardrail workflow</h2><p className="mt-2 text-sm leading-6 text-amber-800">Payout hanya dapat berpindah pending → approved/rejected atau approved → paid/rejected. Status paid membutuhkan referensi pembayaran dan operator berbeda dari reviewer approval. Data rekening hanya disajikan dalam bentuk masked.</p></section></main></AppLayout>;
}
