'use client';
import { AppLayout } from '@/components/layout/AppLayout';
import { Search, SlidersHorizontal, Map, ChevronRight, ShieldCheck, Calculator, Building2 } from 'lucide-react';
import { propertyListings } from '@/config/navigation';

export default function HomePage() {
  return <AppLayout><main className="page-shell">
    <section className="hero-panel">
      <div className="hero-copy"><span className="eyebrow"><ShieldCheck size={14}/> Eksplorasi properti Sultra</span><h1>Ruang yang terasa <em>tepat</em> untuk hidupmu.</h1><p>Listing pilihan di Kendari dan Sulawesi Tenggara, dengan konteks lokal dan data yang lebih transparan.</p><div className="hero-stats"><span><strong>2.840+</strong> listing aktif</span><span><strong>18</strong> kawasan</span><span><strong>96%</strong> data terverifikasi</span></div></div>
      <div className="hero-art" aria-hidden="true"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-art-card"><Building2 size={19}/><span>Ruang tumbuh<br/><b>di Sulawesi Tenggara</b></span></div></div>
    </section>
    <section className="search-card" aria-label="Pencarian properti"><div className="segmented"><button className="segment active">Beli</button><button className="segment">Sewa</button><button className="segment">Komersial</button></div><div className="search-fields"><label className="search-field"><span>Lokasi atau kata kunci</span><div><Search size={18}/><input placeholder="Cari Kendari, Wua-Wua, atau nama proyek" /></div></label><label className="search-field"><span>Tipe properti</span><select defaultValue="Rumah"><option>Rumah</option><option>Apartemen</option><option>Tanah</option><option>Ruko</option></select></label><label className="search-field"><span>Rentang harga</span><select defaultValue="Semua harga"><option>Semua harga</option><option>Di bawah Rp 500 Juta</option><option>Rp 500 Juta – Rp 1 M</option><option>Di atas Rp 1 M</option></select></label><button className="primary-btn search-action"><Search size={18}/> Cari properti</button></div><div className="quick-filters"><span>Lokasi populer</span><button>Kendari</button><button>Baruga</button><button>Wua-Wua</button><button>Poasia</button><button className="filter-btn"><SlidersHorizontal size={15}/> Filter</button></div></section>
    <section className="section-block"><div className="section-heading"><div><span className="eyebrow">Pilihan terkurasi</span><h2>Hunian yang layak dipertimbangkan</h2></div><button className="text-link">Lihat semua <ChevronRight size={16}/></button></div><div className="listing-layout"><div className="listing-grid">{propertyListings.map((property)=><PropertyCard key={property.id} property={property}/>)}</div><aside className="map-card"><div className="map-top"><span className="map-label"><Map size={15}/> Peta eksplorasi</span><span className="map-sync">Diperbarui 5 mnt lalu</span></div><div className="map-surface"><div className="map-road road-a"/><div className="map-road road-b"/><div className="map-water"/><span className="map-pin pin-a">Rp 850 Jt</span><span className="map-pin pin-b">Rp 1,2 M</span><span className="map-pin pin-c">Rp 620 Jt</span><span className="map-place">Kendari</span></div><button className="map-cta">Buka peta penuh <ChevronRight size={15}/></button></aside></div></section>
    <section className="trust-strip"><div className="trust-icon"><ShieldCheck size={22}/></div><div><strong>Data properti lebih mudah dipercaya.</strong><span>Setiap listing pilihan SUKI dilengkapi status verifikasi dan konteks SiKumbang jika tersedia.</span></div><button className="ghost-btn">Pelajari sistem trust</button></section>
    <section className="section-block bottom-grid"><div className="kpr-card"><div><span className="eyebrow"><Calculator size={14}/> Rencana pembiayaan</span><h2>Sudah tahu cicilan yang nyaman?</h2><p>Simulasikan KPR secara ringkas sebelum menghubungi agen.</p><button className="primary-btn">Mulai simulasi <ChevronRight size={16}/></button></div><div className="kpr-number"><span>Estimasi mulai dari</span><strong>Rp 4,8 Jt</strong><small>/ bulan</small></div></div><div className="commercial-card"><span className="eyebrow gold-eyebrow">SUKI Select</span><h2>Ruang komersial dengan karakter.</h2><p>Kurasi ruko, kantor, dan lahan usaha untuk langkah berikutnya.</p><button className="gold-btn">Jelajahi komersial <ChevronRight size={16}/></button></div></section>
  </main></AppLayout>
}

function PropertyCard({ property }: { property: typeof propertyListings[number] }) { return <article className="property-card"><div className="property-image"><img src={property.image} alt={property.title}/><span className={'listing-status ' + property.statusTone}>{property.status}</span><button className="heart-btn" aria-label={'Simpan ' + property.title}>♡</button><span className="photo-count">1 / {property.photos}</span><div className="photo-dots"><i className="active"/><i/><i/></div></div><div className="property-body"><div className="price-row"><strong>{property.price}</strong><span>{property.mode}</span></div><h3>{property.title}</h3><p className="location">{property.location}</p><div className="property-specs"><span><b>{property.beds}</b> KT</span><span><b>{property.baths}</b> KM</span><span><b>{property.area}</b> m²</span></div><div className="trust-row"><ShieldCheck size={14}/><span>ID SiKumbang {property.sikumbang}</span><small>{property.units} unit tersisa</small></div></div></article> }