'use client';

import { useEffect, useRef, useState } from 'react';
import { Check, FilePlus2, Heart, Reply, Send } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import { getChatMessages, markChatRead, sendMessage, setMessageReaction, setTyping } from '@/lib/actions/chat';

type Message = { id: string; conversation_id: string; sender_id: string; content: string | null; message_type?: string; media_url?: string | null; reply_to_message_id?: string | null; edited?: boolean; deleted?: boolean; created_at: string };
type Props = { conversationId: string; currentUserId: string; initialMessages?: Message[] };
export function ChatWindow({ conversationId, currentUserId, initialMessages = [] }: Props) {
  const [messages, setMessages] = useState<Message[]>(initialMessages); const [text, setText] = useState(''); const [replyTo, setReplyTo] = useState<Message | null>(null); const [typingUsers, setTypingUsers] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [attachment, setAttachment] = useState<File | null>(null); const endRef = useRef<HTMLDivElement>(null); const typingTimer = useRef<number | null>(null);
  useEffect(() => { let active = true; getChatMessages(conversationId).then(result => { if (active && result.ok) setMessages(result.data as Message[]); }); void markChatRead(conversationId); return () => { active = false; }; }, [conversationId]);
  useEffect(() => { const client = supabase; if (!client) return; const channel = client.channel(`suki-chat:${conversationId}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages', filter: `conversation_id=eq.${conversationId}` }, payload => { const message = payload.new as Message; setMessages(current => current.some(item => item.id === message.id) ? current : [...current, message]); void markChatRead(conversationId); }).on('postgres_changes', { event: '*', schema: 'public', table: 'typing_indicators', filter: `conversation_id=eq.${conversationId}` }, payload => { const row = payload.new as { user_id: string; is_typing: boolean }; if (row.user_id === currentUserId) return; setTypingUsers(current => row.is_typing ? Array.from(new Set([...current, row.user_id])) : current.filter(id => id !== row.user_id)); }).on('postgres_changes', { event: '*', schema: 'public', table: 'message_reactions' }, () => setMessages(current => [...current])).subscribe(); return () => { void client.removeChannel(channel); }; }, [conversationId, currentUserId]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, typingUsers]);
  function onTextChange(value: string) { setText(value); void setTyping(conversationId, Boolean(value.trim())); if (typingTimer.current) window.clearTimeout(typingTimer.current); typingTimer.current = window.setTimeout(() => { void setTyping(conversationId, false); }, 1500); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if ((!text.trim() && !attachment) || loading) return; const content = text.trim() || `Lampiran: ${attachment?.name}`; setText(''); setAttachment(null); setLoading(true); setError(''); const result = await sendMessage(conversationId, content); setLoading(false); void setTyping(conversationId, false); if (!result.ok) { setText(content); setError(result.error || 'Pesan belum terkirim.'); return; } if (result.data) setMessages(current => current.some(item => item.id === result.data.id) ? current : [...current, result.data as Message]); setReplyTo(null); }
  return <div className="chat-window"><div className="chat-messages" aria-live="polite">{messages.length ? messages.map(message => { const mine = message.sender_id === currentUserId; return <div className={`chat-bubble ${mine ? 'mine' : 'theirs'}`} key={message.id}><span>{message.reply_to_message_id && <small className="mb-1 block opacity-60"><Reply size={11} className="inline"/> Membalas pesan</small>}{message.deleted ? 'Pesan dihapus' : message.content}</span><small className="flex items-center justify-end gap-1">{new Date(message.created_at).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}{mine && <Check size={11}/>}</small><span className="mt-1 flex gap-1"><button onClick={() => void setMessageReaction(message.id, '❤️')} aria-label="Sukai pesan"><Heart size={12}/></button><button onClick={() => setReplyTo(message)} aria-label="Balas pesan"><Reply size={12}/></button></span></div>; }) : <div className="chat-empty">Belum ada pesan. Mulai percakapan dengan seller.</div>}{typingUsers.length > 0 && <div className="chat-typing">Sedang mengetik<span> ···</span></div>}<div ref={endRef}/></div>{error && <p className="chat-error" role="alert">{error}</p>}{replyTo && <div className="border-t border-gray-200 px-3 py-2 text-xs text-gray-500">Membalas: {replyTo.content}<button className="float-right" onClick={() => setReplyTo(null)}>×</button></div>}<form className="chat-composer" onSubmit={submit}><label className="grid h-9 w-9 shrink-0 cursor-pointer place-items-center rounded-lg bg-sultra-mint text-sultra-teal" aria-label="Lampirkan foto, video, atau file"><FilePlus2 size={17}/><input type="file" className="hidden" accept="image/*,video/*,audio/*,.pdf" onChange={event => setAttachment(event.target.files?.[0] || null)}/></label><input value={text} onChange={event => onTextChange(event.target.value)} placeholder={attachment ? attachment.name : 'Tulis pesan...'} aria-label="Tulis pesan" maxLength={4000}/><button disabled={loading || (!text.trim() && !attachment)} aria-label="Kirim pesan"><Send size={16}/></button></form></div>;
}
