'use client';

import { MessageCircle, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase/client';
import { getChatInbox, setPresence } from '@/lib/actions/chat';
import { ChatWindow } from './ChatWindow';

type Conversation = { id: string; type: 'private' | 'group'; name?: string | null; last_message?: string | null; last_message_at?: string };
export function ChatInbox() {
  const [userId, setUserId] = useState(''); const [items, setItems] = useState<Conversation[]>([]); const [selected, setSelected] = useState<string | null>(null); const [error, setError] = useState('');
  useEffect(() => { let active = true; const client = supabase; if (!client) return; client.auth.getUser().then(async ({ data }) => { if (!active || !data.user) { setError('Login diperlukan untuk membuka SUKI Chat.'); return; } setUserId(data.user.id); await setPresence(true); const result = await getChatInbox(); if (result.ok) setItems(result.data as Conversation[]); else setError(result.error); }); return () => { active = false; void setPresence(false); }; }, []);
  return <section className="mx-auto grid min-h-[calc(100vh-56px)] max-w-5xl grid-cols-1 overflow-hidden bg-white dark:bg-sultra-dark md:grid-cols-[280px_1fr]"><aside className="border-r border-gray-200 dark:border-sultra-forest/30"><header className="flex items-center gap-2 border-b border-gray-200 p-4 dark:border-sultra-forest/30"><MessageCircle className="text-sultra-teal" size={21}/><div><h1 className="font-semibold text-sultra-forest dark:text-sultra-mint">SUKI Chat</h1><p className="text-[10px] text-gray-500">Pesan warga Sultra</p></div></header>{error && <p className="p-4 text-xs text-red-600">{error}</p>}{items.length ? items.map(item => <button key={item.id} onClick={() => setSelected(item.id)} className={`flex w-full items-start gap-3 border-b border-gray-100 p-3 text-left dark:border-sultra-forest/20 ${selected === item.id ? 'bg-sultra-mint/40 dark:bg-sultra-forest/20' : 'hover:bg-gray-50'}`}><span className="grid h-9 w-9 place-items-center rounded-full bg-sultra-teal text-white"><Users size={16}/></span><span className="min-w-0"><strong className="block truncate text-sm text-sultra-forest dark:text-sultra-sand">{item.name || (item.type === 'group' ? 'Grup Sultra' : 'Percakapan pribadi')}</strong><small className="block truncate text-xs text-gray-500">{item.last_message || 'Belum ada pesan'}</small></span></button>) : !error && <p className="p-4 text-xs text-gray-500">Belum ada percakapan. Hubungi seller dari Marketplace untuk memulai.</p>}</aside><div className="min-h-[420px]">{selected && userId ? <ChatWindow conversationId={selected} currentUserId={userId}/> : <div className="grid h-full min-h-[420px] place-items-center p-6 text-center text-gray-500"><div><MessageCircle size={38} className="mx-auto mb-3 text-sultra-teal"/><p>Pilih percakapan untuk mulai berkirim pesan.</p><small>Pesan baru akan muncul secara realtime.</small></div></div>}</div></section>;
}
