-- SultraKita Phase 4 backend upgrade mirror.
-- Runtime Express uses BIGINT identifiers; keep this additive and compatible with existing public tables.

alter table public.listings add column if not exists is_featured boolean not null default false;
alter table public.listings add column if not exists is_promoted boolean not null default false;
alter table public.listings add column if not exists views_count bigint not null default 0;
alter table public.listings add column if not exists favorites_count bigint not null default 0;
alter table public.listings add column if not exists video_url text;
alter table public.listings add column if not exists promoted_until timestamptz;
alter table public.listings add column if not exists seller_rating numeric(3,2) not null default 0;
alter table public.notifications add column if not exists data jsonb not null default '{}'::jsonb;

create table if not exists public.listing_views (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  user_id uuid references public.users(id) on delete set null,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.search_history (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  query text not null check (char_length(query) between 2 and 160),
  results_count integer not null default 0 check (results_count >= 0),
  created_at timestamptz not null default now()
);

create index if not exists listings_phase4_category_idx on public.listings(category_id, status, created_at desc);
create index if not exists listings_phase4_location_idx on public.listings(location_id, status, created_at desc);
create index if not exists listings_phase4_price_idx on public.listings(price, status);
create index if not exists listings_phase4_featured_idx on public.listings(is_featured, created_at desc) where is_featured = true;
create index if not exists listings_phase4_promoted_idx on public.listings(is_promoted, promoted_until, created_at desc) where is_promoted = true;
create index if not exists listing_views_phase4_listing_idx on public.listing_views(listing_id, created_at desc);
create index if not exists listing_views_phase4_created_idx on public.listing_views(created_at desc);
create index if not exists search_history_phase4_user_idx on public.search_history(user_id, created_at desc);

alter table public.listing_views enable row level security;
alter table public.search_history enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'listing_views' and policyname = 'public can insert listing views') then
    create policy "public can insert listing views" on public.listing_views for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'search_history' and policyname = 'users read own search history') then
    create policy "users read own search history" on public.search_history for select using (user_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'search_history' and policyname = 'users manage own search history') then
    create policy "users manage own search history" on public.search_history for all using (user_id = auth.uid()) with check (user_id = auth.uid());
  end if;
end $$;
