-- Seed hierarki lokasi Sulawesi Tenggara untuk demo dan filter cascading.
insert into public.locations (regency_name, district_name, subdistrict_name) values
('Kota Kendari','Kendari Barat','Punggaloba'),
('Kota Kendari','Kendari Barat','Sadoha'),
('Kota Kendari','Kendari Barat','Benu-Benua'),
('Kota Kendari','Kendari Barat','Tipulu'),
('Kota Kendari','Kendari Barat','Watu-Watu'),
('Kota Kendari','Kendari Barat','Sanua'),
('Kota Kendari','Baruga','Watubangga'),
('Kota Kendari','Baruga','Lepo-Lepo'),
('Kota Kendari','Baruga','Baruga'),
('Kota Kendari','Baruga','Kampung Salo'),
('Kota Kendari','Baruga','Wundudopi'),
('Kota Kendari','Kadia','Kadia'),
('Kota Kendari','Kadia','Bende'),
('Kota Kendari','Kadia','Anaiwoi'),
('Kota Kendari','Kadia','Wowawanggu'),
('Kota Kendari','Kadia','Dapu-Dapura'),
('Kota Kendari','Poasia','Anduonohu'),
('Kota Kendari','Poasia','Rahandouna'),
('Kota Kendari','Poasia','Wundumbatu'),
('Kota Kendari','Poasia','Matabubu'),
('Kota Kendari','Poasia','Anggoeya'),
('Kota Kendari','Poasia','Benu-Benua'),
('Kota Kendari','Kambu','Kambu'),
('Kota Kendari','Kambu','Padaleu'),
('Kota Kendari','Kambu','Mokoau'),
('Kota Kendari','Kambu','Lalolara'),
('Kota Kendari','Kambu','Korumba'),
('Kota Kendari','Mandonga','Mandonga'),
('Kota Kendari','Mandonga','Korumba'),
('Kota Kendari','Mandonga','Alolama'),
('Kota Kendari','Mandonga','Anggilowu'),
('Kota Kendari','Mandonga','Wawombalata'),
('Kota Kendari','Kendari','Kandai'),
('Kota Kendari','Kendari','Jati Mekar'),
('Kota Kendari','Kendari','Jati Raya'),
('Kota Kendari','Kendari','Kasilampe'),
('Kota Kendari','Kendari','Kendari Caddi'),
('Kota Kendari','Kendari Timur','Kessilampe'),
('Kota Kendari','Kendari Timur','Lapulu'),
('Kota Kendari','Kendari Timur','Abeli'),
('Kota Kendari','Kendari Timur','Tobimeita'),
('Kota Kendari','Kendari Timur','Puday'),
('Kota Kendari','Abeli','Abeli'),
('Kota Kendari','Abeli','Poasia'),
('Kota Kendari','Abeli','Anggoeya'),
('Kota Kendari','Abeli','Tondonggeu'),
('Kota Kendari','Abeli','Bungkutoko'),
('Kota Kendari','Wua-Wua','Wua-Wua'),
('Kota Kendari','Wua-Wua','Anawai'),
('Kota Kendari','Wua-Wua','Mataiwoi'),
('Kota Kendari','Wua-Wua','Kadia'),
('Kota Kendari','Wua-Wua','Wowawanggu'),
('Kota Kendari','Puuwatu','Puuwatu'),
('Kota Kendari','Puuwatu','Watulondo'),
('Kota Kendari','Puuwatu','Punggolaka'),
('Kota Kendari','Puuwatu','Abeli Dalam'),
('Kota Kendari','Puuwatu','Lalodati'),
('Kota Baubau','Betoambari','Lipu'),
('Kota Baubau','Betoambari','Sulaa'),
('Kota Baubau','Betoambari','Katobengke'),
('Kota Baubau','Betoambari','Waborobo'),
('Kota Baubau','Betoambari','Labalawa'),
('Kota Baubau','Wolio','Batulo'),
('Kota Baubau','Wolio','Wale'),
('Kota Baubau','Wolio','Bataraguru'),
('Kota Baubau','Wolio','Tomba'),
('Kota Baubau','Wolio','Wangkanapi'),
('Kota Baubau','Wolio','Buganin'),
('Kota Baubau','Murhum','Baadia'),
('Kota Baubau','Murhum','Wajo'),
('Kota Baubau','Murhum','Nganganaumala'),
('Kota Baubau','Murhum','Melai'),
('Kota Baubau','Murhum','Lamangga'),
('Kota Baubau','Kokalukuna','Kokalukuna'),
('Kota Baubau','Kokalukuna','Liabuku'),
('Kota Baubau','Kokalukuna','Waruruma'),
('Kota Baubau','Kokalukuna','Lakologou'),
('Kota Baubau','Kokalukuna','Kadolo'),
('Kota Baubau','Sorawolio','Gonda Baru'),
('Kota Baubau','Sorawolio','Karya Baru'),
('Kota Baubau','Sorawolio','Bugi'),
('Kota Baubau','Sorawolio','Sunggu'),
('Kota Baubau','Bungi','Liabuku'),
('Kota Baubau','Bungi','Ngkari-Ngkari'),
('Kota Baubau','Bungi','Kampeonaho'),
('Kota Baubau','Bungi','Kaisabu'),
('Kota Baubau','Lea-Lea','Kalia-Lia'),
('Kota Baubau','Lea-Lea','Kantalai'),
('Kota Baubau','Lea-Lea','Palabusa'),
('Kota Baubau','Lea-Lea','Lowu-Lowu'),
('Kota Baubau','Batupoaro','Tarafu'),
('Kota Baubau','Batupoaro','Wameo'),
('Kota Baubau','Batupoaro','Bone-Bone'),
('Kota Baubau','Batupoaro','Kaobula'),
('Kota Baubau','Batupoaro','Nganganaumala'),
('Kabupaten Konawe','Unaaha','Tumpas'),
('Kabupaten Konawe','Unaaha','Arombu'),
('Kabupaten Konawe','Unaaha','Unaaha'),
('Kabupaten Konawe','Unaaha','Puunaaha'),
('Kabupaten Konawe','Unaaha','Asinua'),
('Kabupaten Konawe','Wawotobi','Wawotobi'),
('Kabupaten Konawe','Wawotobi','Humboto'),
('Kabupaten Konawe','Wawotobi','Kasumeia'),
('Kabupaten Konawe','Wawotobi','Nohu-Nohu'),
('Kabupaten Konawe','Wawotobi','Mataiwoi'),
('Kabupaten Konawe Utara','Asera','Asera'),
('Kabupaten Konawe Utara','Asera','Wanggudu Raya'),
('Kabupaten Konawe Utara','Asera','Lameruru'),
('Kabupaten Konawe Utara','Asera','Tangguluri'),
('Kabupaten Konawe Utara','Asera','Aseminunulai'),
('Kabupaten Konawe Utara','Wanggudu','Wanggudu'),
('Kabupaten Konawe Utara','Wanggudu','Puuwanggudu'),
('Kabupaten Konawe Utara','Wanggudu','Laronanga'),
('Kabupaten Konawe Utara','Wanggudu','Pongkaluku'),
('Kabupaten Konawe Utara','Wanggudu','Tangguluri'),
('Kabupaten Kolaka','Wundulako','Wundulako'),
('Kabupaten Kolaka','Wundulako','Lamekongga'),
('Kabupaten Kolaka','Wundulako','Silea'),
('Kabupaten Kolaka','Wundulako','Towua'),
('Kabupaten Kolaka','Wundulako','19 November'),
('Kabupaten Kolaka','Pomalaa','Tonggoni'),
('Kabupaten Kolaka','Pomalaa','Huko-Huko'),
('Kabupaten Kolaka','Pomalaa','Pelambua'),
('Kabupaten Kolaka','Pomalaa','Oko-Oko'),
('Kabupaten Kolaka','Pomalaa','Pomalaa'),
('Kabupaten Muna','Raha','Raha I'),
('Kabupaten Muna','Raha','Raha II'),
('Kabupaten Muna','Raha','Laende'),
('Kabupaten Muna','Raha','Wamponiki'),
('Kabupaten Muna','Raha','Napabalano'),
('Kabupaten Muna','Katobu','Wamponiki'),
('Kabupaten Muna','Katobu','Watonea'),
('Kabupaten Muna','Katobu','Laiworu'),
('Kabupaten Muna','Katobu','Sidodadi'),
('Kabupaten Muna','Katobu','Raha III')
on conflict (regency_name, district_name, subdistrict_name) do nothing;
