-- SultraKita account settings foundation. Production already contains these tables;
-- this migration keeps fresh environments aligned without creating a parallel database.
CREATE TABLE IF NOT EXISTS public.user_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  auth_user_id uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL, dark_mode boolean NOT NULL DEFAULT false,
  language varchar(12) NOT NULL DEFAULT 'id' CHECK (language ~ '^[a-z]{2}(-[A-Z]{2})?$'), app_icon varchar(40) NOT NULL DEFAULT 'default',
  notifications_enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.privacy_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  auth_user_id uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL, profile_visibility varchar(16) NOT NULL DEFAULT 'public' CHECK (profile_visibility IN ('public','friends','private')),
  show_activity_status boolean NOT NULL DEFAULT true, allow_tagging boolean NOT NULL DEFAULT true, data_sharing_consent boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.notification_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  email_notifications boolean NOT NULL DEFAULT true, push_notifications boolean NOT NULL DEFAULT true, sms_notifications boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.account_deletion_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  requested_at timestamptz NOT NULL DEFAULT now(), scheduled_for timestamptz NOT NULL, cancelled_at timestamptz NULL, completed_at timestamptz NULL
);
CREATE TABLE IF NOT EXISTS public.data_exports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  format varchar(8) NOT NULL DEFAULT 'json' CHECK (format IN ('json','csv')), status varchar(12) NOT NULL DEFAULT 'ready' CHECK (status IN ('queued','ready','expired','failed')),
  created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours'), completed_at timestamptz NULL
);
CREATE TABLE IF NOT EXISTS public.security_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NULL REFERENCES public.users(id) ON DELETE SET NULL,
  event_type varchar(120) NOT NULL, outcome varchar(16) NOT NULL DEFAULT 'success' CHECK (outcome IN ('success','failure','blocked','detected')),
  resource_type varchar(80) NULL, resource_id varchar(120) NULL, ip_address inet NULL, user_agent varchar(300) NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS account_deletion_requests_user_idx ON public.account_deletion_requests(user_id, requested_at DESC);
CREATE INDEX IF NOT EXISTS data_exports_user_idx ON public.data_exports(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS security_events_user_idx ON public.security_events(user_id, created_at DESC);
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.privacy_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_deletion_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_exports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_events ENABLE ROW LEVEL SECURITY;
