-- SultraKita Support System: additive, RLS-protected support foundation.
create extension if not exists pgcrypto;
create table if not exists public.help_articles (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, content text not null, category text not null check (category in ('umum','marketplace','suki_suits','chat','payment','security','account')), tags text[] not null default '{}', views_count integer not null default 0, is_published boolean not null default false, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.support_tickets (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, ticket_number text unique not null, subject text not null, description text not null, category text not null check (category in ('technical','fraud','payment','listing','account','other')), priority text not null default 'medium' check (priority in ('low','medium','high','critical')), status text not null default 'open' check (status in ('open','in_progress','waiting_user','resolved','closed')), related_listing_id uuid, related_order_id uuid, reported_user_id uuid, screenshots text[] not null default '{}', admin_response text, resolved_at timestamptz, resolved_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.security_logs (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, event_type text not null check (event_type in ('login','logout','password_change','email_change','phone_change','2fa_enabled','2fa_disabled','suspicious_activity')), ip_address inet, user_agent text, device_info jsonb, location text, is_suspicious boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.trusted_devices (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, device_name text not null, device_id text not null, last_active_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(user_id, device_id));
create table if not exists public.legal_documents (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, content text not null, version text not null, category text not null check (category in ('terms','privacy','cookies','community_guidelines','copyright')), is_active boolean not null default false, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists help_articles_category_idx on public.help_articles(category, is_published);
create index if not exists support_tickets_user_idx on public.support_tickets(user_id, created_at desc);
create index if not exists support_tickets_status_idx on public.support_tickets(status);
create index if not exists security_logs_user_idx on public.security_logs(user_id, created_at desc);
create index if not exists trusted_devices_user_idx on public.trusted_devices(user_id);

alter table public.help_articles enable row level security; alter table public.support_tickets enable row level security; alter table public.security_logs enable row level security; alter table public.trusted_devices enable row level security; alter table public.legal_documents enable row level security;
drop policy if exists help_articles_public_read on public.help_articles; create policy help_articles_public_read on public.help_articles for select to anon, authenticated using (is_published = true);
drop policy if exists support_tickets_owner_read on public.support_tickets; create policy support_tickets_owner_read on public.support_tickets for select to authenticated using (auth.uid() = user_id);
drop policy if exists support_tickets_owner_insert on public.support_tickets; create policy support_tickets_owner_insert on public.support_tickets for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists security_logs_owner_read on public.security_logs; create policy security_logs_owner_read on public.security_logs for select to authenticated using (auth.uid() = user_id);
drop policy if exists trusted_devices_owner_read on public.trusted_devices; create policy trusted_devices_owner_read on public.trusted_devices for select to authenticated using (auth.uid() = user_id);
drop policy if exists trusted_devices_owner_manage on public.trusted_devices; create policy trusted_devices_owner_manage on public.trusted_devices for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists legal_documents_public_read on public.legal_documents; create policy legal_documents_public_read on public.legal_documents for select to anon, authenticated using (is_active = true);

create or replace function public.generate_ticket_number() returns trigger language plpgsql security definer set search_path = public as $$ begin if new.ticket_number is null or new.ticket_number = '' then new.ticket_number := 'SUP-' || to_char(now(), 'YYYY') || '-' || lpad((floor(extract(epoch from clock_timestamp()))::bigint % 1000000)::text, 6, '0'); end if; return new; end; $$;
drop trigger if exists trg_generate_ticket_number on public.support_tickets; create trigger trg_generate_ticket_number before insert on public.support_tickets for each row execute function public.generate_ticket_number();
create or replace function public.set_support_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists trg_support_tickets_updated_at on public.support_tickets; create trigger trg_support_tickets_updated_at before update on public.support_tickets for each row execute function public.set_support_updated_at();
