'use client';

import { ChevronLeft, ChevronRight, Heart, MapPin, ShieldCheck } from 'lucide-react';
import { useState } from 'react';

export type MarketplaceListing = { id: string; title: string; description?: string | null; price: number; images?: string[]; thumbnail_url?: string | null; district?: string | null; city?: string | null; condition?: string | null; is_featured?: boolean; is_demo?: boolean };
function conditionLabel(value?: string | null) { return value === 'new' ? 'Baru' : value === 'like_new' ? 'Seperti baru' : value === 'fair' ? 'Cukup baik' : 'Terawat'; }
function rupiah(value: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value); }

export function MarketplaceCard({ item, saved, onSave, onQuickView, compared, onCompare }: { item: MarketplaceListing; saved: boolean; onSave: (id: string) => void; onQuickView: (item: MarketplaceListing) => void; compared: boolean; onCompare: (item: MarketplaceListing) => void }) {
  const images = (item.images || []).filter(Boolean); const [imageIndex, setImageIndex] = useState(0); const image = images.length ? images[imageIndex] : item.thumbnail_url;
  function moveImage(direction: number) { setImageIndex(index => (index + direction + images.length) % images.length); }
  return <article className="group overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:shadow-md dark:border-stone-800 dark:bg-stone-900">
    <div className="relative aspect-[4/3] overflow-hidden bg-gradient-to-br from-amber-50 to-stone-100 dark:from-stone-800 dark:to-stone-900">{image ? <img src={image} alt={`${item.title} — foto ${imageIndex + 1}`} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /> : <div className="marketplace-card-placeholder"><span>{item.is_featured ? 'Pilihan warga Sultra' : 'Produk lokal'}</span><b>{item.title.slice(0, 1)}</b></div>}{images.length > 1 && <><button className="absolute left-2 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-full bg-white/90 text-stone-800 shadow-sm focus:ring-2 focus:ring-amber-500 focus:outline-none dark:bg-stone-900/90 dark:text-stone-100" onClick={() => moveImage(-1)} aria-label="Foto sebelumnya"><ChevronLeft size={15} /></button><button className="absolute right-2 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-full bg-white/90 text-stone-800 shadow-sm focus:ring-2 focus:ring-amber-500 focus:outline-none dark:bg-stone-900/90 dark:text-stone-100" onClick={() => moveImage(1)} aria-label="Foto berikutnya"><ChevronRight size={15} /></button><div className="absolute bottom-2 left-1/2 flex -translate-x-1/2 gap-1" aria-label={`Foto ${imageIndex + 1} dari ${images.length}`}>{images.map((_, index) => <i key={index} className={`h-1.5 rounded-full ${index === imageIndex ? 'w-4 bg-white' : 'w-1.5 bg-white/60'}`} />)}</div></>}{(item.is_featured || item.is_demo) && <span className="absolute left-3 top-3 rounded-full bg-amber-500 px-2.5 py-1 text-[10px] font-bold text-white">Di sekitar</span>}<button className={`absolute bottom-3 right-3 grid h-9 w-9 place-items-center rounded-full bg-white/90 text-stone-700 shadow-sm transition hover:scale-105 focus:ring-2 focus:ring-amber-500 focus:outline-none dark:bg-stone-900/90 dark:text-stone-200 ${saved ? 'text-amber-600' : ''}`} onClick={() => onSave(item.id)} aria-label={saved ? `Hapus ${item.title} dari tersimpan` : `Simpan ${item.title}`} aria-pressed={saved}><Heart size={18} fill={saved ? 'currentColor' : 'none'} /></button></div>
    <div className="p-4"><div className="text-lg font-bold text-amber-600 dark:text-amber-400">{rupiah(Number(item.price))}</div><h2 className="mt-1 line-clamp-2 font-semibold text-stone-900 dark:text-stone-100">{item.title}</h2><p className="mt-2 flex items-center gap-1 text-xs text-stone-500 dark:text-stone-400"><MapPin size={13} aria-hidden="true" />{item.district || item.city || 'Sulawesi Tenggara'}<span aria-hidden="true">·</span>{conditionLabel(item.condition)}</p><div className="mt-3 flex items-center gap-1.5 text-[11px] text-amber-700 dark:text-amber-400"><ShieldCheck size={13} aria-hidden="true" /> Listing lokal terverifikasi</div><div className="mt-4 flex gap-2 border-t border-stone-200 pt-3 dark:border-stone-800"><button className="flex-1 rounded-lg bg-stone-100 px-3 py-2 text-xs font-semibold text-stone-800 transition hover:bg-stone-200 focus:ring-2 focus:ring-amber-500 focus:outline-none dark:bg-stone-800 dark:text-stone-100 dark:hover:bg-stone-700" onClick={() => onQuickView(item)}>Lihat cepat</button><button className={`rounded-lg border border-stone-200 px-3 py-2 text-xs font-semibold transition hover:border-amber-500 hover:text-amber-700 focus:ring-2 focus:ring-amber-500 focus:outline-none dark:border-stone-700 dark:text-stone-200 ${compared ? 'bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-400' : ''}`} onClick={() => onCompare(item)} aria-pressed={compared}>{compared ? 'Dipilih' : 'Bandingkan'}</button></div></div>
  </article>;
}
