'use client';

import { ChevronDown, Grid2X2, MapPin, Search, Tag, Wrench, X } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';

const tabs = [{ label: 'Jual', href: '#jual' }, { label: 'Jelajahi', href: '/marketplace' }, { label: 'Lokal', href: '/marketplace?location=Sulawesi%20Tenggara' }];
const suggestions = { trending: ['Laptop HP', 'Tanah Kavling', 'Ruko'], categories: ['Elektronik', 'Otomotif', 'Properti'], locations: ['Kendari', 'Konawe', 'Baubau'] };

export function MarketplaceSubNav({ query, onQueryChange }: { query: string; onQueryChange: (value: string) => void }) {
  const [open, setOpen] = useState(false); const [locationOpen, setLocationOpen] = useState(false); const [suggestionsOpen, setSuggestionsOpen] = useState(false); const [recent, setRecent] = useState<string[]>([]); const ref = useRef<HTMLDivElement>(null); const locationRef = useRef<HTMLDivElement>(null); const searchRef = useRef<HTMLLabelElement>(null);
  useEffect(() => { try { const stored = JSON.parse(window.localStorage.getItem('suki-marketplace-recent-searches') || '[]'); if (Array.isArray(stored)) setRecent(stored.filter((item): item is string => typeof item === 'string').slice(0, 4)); } catch { /* local storage is optional */ } }, []);
  useEffect(() => { const close = (event: MouseEvent) => { const target = event.target as Node; if (ref.current && !ref.current.contains(target)) setOpen(false); if (locationRef.current && !locationRef.current.contains(target)) setLocationOpen(false); if (searchRef.current && !searchRef.current.contains(target)) setSuggestionsOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  const filtered = useMemo(() => { const value = query.trim().toLowerCase(); const all = [...recent, ...suggestions.trending, ...suggestions.categories, ...suggestions.locations]; return all.filter((item, index) => (!value || item.toLowerCase().includes(value)) && all.indexOf(item) === index).slice(0, 7); }, [query, recent]);
  function choose(value: string) { onQueryChange(value); setSuggestionsOpen(false); const next = [value, ...recent.filter(item => item !== value)].slice(0, 4); setRecent(next); try { window.localStorage.setItem('suki-marketplace-recent-searches', JSON.stringify(next)); } catch { /* local storage is optional */ } window.dispatchEvent(new CustomEvent('marketplace-search', { detail: { query: value } })); }
  return <section className="marketplace-subnav">
    <div className="marketplace-subnav-head"><div><span className="marketplace-kicker">Ruang jual beli warga</span><h1>Marketplace</h1></div><button className="marketplace-icon-button" aria-label="Buka menu marketplace"><Grid2X2 size={19} /></button></div>
    <label className="marketplace-search" ref={searchRef}><Search size={18} /><input value={query} onFocus={() => setSuggestionsOpen(true)} onChange={event => { onQueryChange(event.target.value); setSuggestionsOpen(true); }} placeholder="Apa yang ingin Anda beli?" aria-label="Cari produk marketplace" aria-autocomplete="list" aria-controls="marketplace-search-suggestions" />{query && <button type="button" onClick={() => onQueryChange('')} aria-label="Hapus pencarian"><X size={16} /></button>}{suggestionsOpen && <div id="marketplace-search-suggestions" className="marketplace-suggestions" role="listbox"><div className="marketplace-suggestion-label">{query ? 'Saran pencarian' : recent.length ? 'Pencarian terakhir' : 'Sedang tren'}</div>{filtered.map(item => <button key={item} type="button" role="option" onClick={() => choose(item)}><Search size={14} />{item}<small>{suggestions.locations.includes(item) ? 'Lokasi' : suggestions.categories.includes(item) ? 'Kategori' : 'Pencarian'}</small></button>)}{!filtered.length && <p>Tidak ada saran yang cocok.</p>}</div>}</label>
    <div className="marketplace-tabs" aria-label="Kategori marketplace">{tabs.map(tab => <Link key={tab.label} href={tab.href} className={`marketplace-tab ${tab.label === 'Jelajahi' ? 'active' : ''}`} aria-current={tab.label === 'Jelajahi' ? 'page' : undefined}>{tab.label}</Link>)}<div className="marketplace-more-wrap" ref={ref}><button className="marketplace-tab marketplace-more-trigger" onClick={() => setOpen(value => !value)} aria-expanded={open}>Lainnya <ChevronDown size={15} /></button>{open && <div className="marketplace-more-menu"><Link href="/marketplace/categories"><Grid2X2 size={16} /><span>Semua kategori<small>Temukan berdasarkan kategori</small></span></Link><Link href="/marketplace?deal=day"><Tag size={16} /><span>Deal of the Day<small>Penawaran pilihan hari ini</small></span></Link><Link href="/marketplace/seller-tools"><Wrench size={16} /><span>Selling tools<small>Kelola aktivitas jualan</small></span></Link></div>}</div><div className="marketplace-location-wrap" ref={locationRef}><button className="marketplace-location-pill" onClick={() => setLocationOpen(value => !value)} aria-label="Lokasi marketplace: Sultra" aria-expanded={locationOpen}><MapPin size={16} /><span>Sultra</span><ChevronDown size={13} /></button>{locationOpen && <div className="marketplace-location-menu"><strong>Lokasi pencarian</strong><small>Sulawesi Tenggara</small><div className="marketplace-location-cities">{['Kendari', 'Baubau', 'Kolaka', 'Konawe', 'Muna', 'Buton'].map(city => <Link key={city} href={`/marketplace?district=${encodeURIComponent(city)}`} onClick={() => setLocationOpen(false)}><MapPin size={13} />{city}</Link>)}</div><strong className="marketplace-radius-title">Radius</strong><div className="marketplace-radius-options">{['5 km', '10 km', '25 km', 'Seluruh Sultra'].map(radius => <Link key={radius} href={`/marketplace?radius=${encodeURIComponent(radius)}`} onClick={() => setLocationOpen(false)}>{radius}</Link>)}</div></div>}</div></div>
  </section>;
}
