'use client';

import { ArrowRight, Check, MapPin, ShieldCheck, Star, X } from 'lucide-react';
import Link from 'next/link';
import { useEffect } from 'react';
import type { MarketplaceListing } from './MarketplaceCard';

function rupiah(value: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value); }
function conditionLabel(value?: string | null) { return value === 'new' ? 'Baru' : value === 'like_new' ? 'Seperti baru' : value === 'fair' ? 'Cukup baik' : 'Terawat'; }

export function QuickViewModal({ item, onClose }: { item: MarketplaceListing | null; onClose: () => void }) {
  useEffect(() => { if (!item) return; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('keydown', closeOnEscape); const previousOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', closeOnEscape); document.body.style.overflow = previousOverflow; }; }, [item, onClose]);
  if (!item) return null;
  const image = item.thumbnail_url || item.images?.[0]; const verified = item.seller?.verification_status === 'approved'; const rating = Number(item.seller?.rating_average || 0); const ratingCount = Number(item.seller?.rating_count || 0); const location = item.district || item.city || 'Sulawesi Tenggara';
  return <div className="marketplace-modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="marketplace-quick-modal" role="dialog" aria-modal="true" aria-labelledby="quick-view-title"><button type="button" className="marketplace-modal-close" onClick={onClose} aria-label="Tutup quick view"><X size={18} /></button><div className="marketplace-quick-modal-art">{image ? <img src={image} alt={`${item.title} — pratinjau`} /> : <div><span>Produk lokal</span><b>{item.title.slice(0, 1)}</b></div>}{item.is_featured && <span className="marketplace-card-badge"><Star size={11} fill="currentColor" aria-hidden="true" /> Pilihan warga</span>}</div><div className="marketplace-quick-modal-content"><span className="marketplace-kicker">Quick view listing</span><h2 id="quick-view-title">{item.title}</h2><strong>{rupiah(Number(item.price))}</strong><p>{item.description || 'Listing lokal pilihan dari penjual di Sulawesi Tenggara.'}</p><div className="marketplace-quick-seller"><div className="seller-avatar">{item.seller?.avatar_url ? <img src={item.seller.avatar_url} alt="" /> : <span>{(item.seller?.name || 'PL').slice(0, 2).toUpperCase()}</span>}</div><div><b>{item.seller?.name || 'Penjual lokal'}</b><small>{verified ? <><ShieldCheck size={12} /> Terverifikasi</> : 'Profil belum terverifikasi'}</small></div>{ratingCount > 0 && <span className="seller-rating"><Star size={13} fill="currentColor" /><b>{rating.toFixed(1)}</b><small>({ratingCount})</small></span>}</div><div className="marketplace-quick-meta"><span><MapPin size={14} />{location}</span><span><Check size={14} />{conditionLabel(item.condition)}</span><span className={verified ? 'is-verified' : ''}><ShieldCheck size={14} />{verified ? 'Identitas seller disetujui' : 'Trust data belum tersedia'}</span></div><Link href={`/marketplace?listing=${encodeURIComponent(item.id)}`} onClick={onClose}>Lihat detail lengkap <ArrowRight size={15} /></Link></div></section></div>;
}
