'use client';

import { BellRing, ChevronRight, Search, Trash2 } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type SavedSearch = { query?: string; district?: string; minPrice?: string; maxPrice?: string; condition?: string; savedAt?: string };
function label(search: SavedSearch) { const parts = [search.query || 'Semua listing', search.district !== 'Semua distrik' ? search.district : '', search.condition || ''].filter(Boolean); return parts.join(' · '); }
function href(search: SavedSearch) { const params = new URLSearchParams(); if (search.query) params.set('q', search.query); if (search.district && search.district !== 'Semua distrik') params.set('district', search.district); if (search.minPrice) params.set('minPrice', search.minPrice); if (search.maxPrice) params.set('maxPrice', search.maxPrice); if (search.condition) params.set('condition', search.condition); return `/marketplace${params.toString() ? `?${params}` : ''}`; }
export function SavedSearches() { const [searches, setSearches] = useState<SavedSearch[]>([]); useEffect(() => { try { const value = JSON.parse(window.localStorage.getItem('suki-marketplace-saved-searches') || '[]'); if (Array.isArray(value)) setSearches(value); } catch { /* optional storage */ } }, []); function remove(index: number) { const next = searches.filter((_, itemIndex) => itemIndex !== index); setSearches(next); try { window.localStorage.setItem('suki-marketplace-saved-searches', JSON.stringify(next)); } catch { /* optional storage */ } } return <section className="marketplace-saved-searches"><div className="marketplace-saved-searches-head"><div><span className="marketplace-kicker"><BellRing size={13} /> Alert pencarian</span><h2>Pencarian tersimpan</h2></div><Search size={20} /></div>{searches.length ? <div className="marketplace-saved-search-list">{searches.map((search, index) => <div key={`${search.savedAt}-${index}`}><Link href={href(search)}><span><b>{label(search)}</b><small>Klik untuk menjalankan pencarian ini lagi</small></span><ChevronRight size={15} /></Link><button onClick={() => remove(index)} aria-label={`Hapus pencarian ${label(search)}`}><Trash2 size={14} /></button></div>)}</div> : <p className="marketplace-saved-empty">Belum ada pencarian tersimpan. Simpan filter favoritmu dari halaman Marketplace.</p>}</section>; }
